In [1]:
import pandas as pd

#### 파일 불러오기

In [2]:
pop_df = pd.read_csv("C:/AcornFinalProject/2. 데이터 파일/가구 수/raw/서울시 가구원수별 가구수(구별) 통계[2015-2019].csv", encoding='ms949')
pop_df

,기간,구분,일반가구수,1인,2인,3인,4인,5인,6인,7인 이상,평균가구원수
0,2015,합계,"3,784,490","1,115,744","930,467","817,440","701,945","169,436","38,547","10,911",2.5
1,2015,종로구,"61,580","22,776","15,314","11,272","8,840","2,535",628,215,2.3
2,2015,중구,"51,205","19,161","13,157","9,392","6,987","1,879",483,146,2.2
3,2015,용산구,"90,313","31,025","23,776","17,826","13,222","3,436",788,240,2.3
4,2015,성동구,"114,719","35,259","28,415","24,622","20,125","4,748","1,220",330,2.4
...,...,...,...,...,...,...,...,...,...,...,...
125,2019,관악구,"242,154","119,863","55,423","34,875","24,563","5,806","1,283",341,2.0
126,2019,서초구,"155,377","42,667","38,892","35,327","29,850","6,704","1,503",434,2.5
127,2019,강남구,"206,524","66,073","51,560","43,435","35,800","7,671","1,564",421,2.4
128,2019,송파구,"252,212","68,861","65,402","57,821","47,607","10,014","2,038",469,2.5
129,2019,강동구,"162,976","45,188","43,297","36,735","29,461","6,606","1,333",356,2.5

#### 2017~2019 추출

In [3]:
pop_df1 = pop_df[(pop_df['기간'] == 2017)|(pop_df['기간'] == 2018)|(pop_df['기간'] == 2019)]

pop_df1

,기간,구분,일반가구수,1인,2인,3인,4인,5인,6인,7인 이상,평균가구원수
52,2017,합계,"3,813,260","1,180,540","956,978","813,629","662,920","154,992","34,649","9,552",2.4
53,2017,종로구,"62,372","23,638","15,697","11,268","8,636","2,351",601,181,2.2
54,2017,중구,"52,208","20,164","13,623","9,498","6,696","1,660",445,122,2.2
55,2017,용산구,"91,102","33,076","24,058","17,316","12,585","3,154",724,189,2.2
56,2017,성동구,"120,957","39,067","30,728","25,452","19,855","4,437","1,115",303,2.4
...,...,...,...,...,...,...,...,...,...,...,...
125,2019,관악구,"242,154","119,863","55,423","34,875","24,563","5,806","1,283",341,2.0
126,2019,서초구,"155,377","42,667","38,892","35,327","29,850","6,704","1,503",434,2.5
127,2019,강남구,"206,524","66,073","51,560","43,435","35,800","7,671","1,564",421,2.4
128,2019,송파구,"252,212","68,861","65,402","57,821","47,607","10,014","2,038",469,2.5
129,2019,강동구,"162,976","45,188","43,297","36,735","29,461","6,606","1,333",356,2.5

#### 합계 행 삭제

In [4]:
pop_df2 = pop_df1.drop(pop_df1[pop_df1['구분'] == '합계'].index)

pop_df2

,기간,구분,일반가구수,1인,2인,3인,4인,5인,6인,7인 이상,평균가구원수
53,2017,종로구,"62,372","23,638","15,697","11,268","8,636","2,351",601,181,2.2
54,2017,중구,"52,208","20,164","13,623","9,498","6,696","1,660",445,122,2.2
55,2017,용산구,"91,102","33,076","24,058","17,316","12,585","3,154",724,189,2.2
56,2017,성동구,"120,957","39,067","30,728","25,452","19,855","4,437","1,115",303,2.4
57,2017,광진구,"147,846","54,866","34,309","28,746","23,244","5,191","1,151",339,2.3
...,...,...,...,...,...,...,...,...,...,...,...
125,2019,관악구,"242,154","119,863","55,423","34,875","24,563","5,806","1,283",341,2.0
126,2019,서초구,"155,377","42,667","38,892","35,327","29,850","6,704","1,503",434,2.5
127,2019,강남구,"206,524","66,073","51,560","43,435","35,800","7,671","1,564",421,2.4
128,2019,송파구,"252,212","68,861","65,402","57,821","47,607","10,014","2,038",469,2.5
129,2019,강동구,"162,976","45,188","43,297","36,735","29,461","6,606","1,333",356,2.5

#### 정제 데이터 저장

In [ ]:
pop_df2.to_csv('C:/AcornFinalProject/2. 데이터 파일/가구 수/data/서울시 가구원수별 가구수(구별) 통계.csv',index=False, encoding='ms949')