In [1]:
import numpy as np
import pandas as pd
from datetime import timedelta
import glob
import os

import warnings
warnings.filterwarnings(action='ignore')

In [7]:
data = pd.read_csv('raw/서울시 대학 및 전문대학 DB 정보.csv', encoding='cp949')
data

,키값,연도,학교종류,학교명,본분교,학교상태,설립,우편번호,주소,도로명주소,행정시,행정구,행정동,전화번호,팩스번호,홈페이지
0,BE_LiST23-0034,2013,일반대학,서울시립대학교,본교,기존,공립,NaN,서울 동대문구 서울시립대로 163 (전농동 90번지),NaN,서울특별시,동대문구,휘경2동,02-6490-6114,02-2210-5576,http://www.uos.ac.kr
1,BE_LiST23-0035,2013,전문대학(3년제),서울여자간호대학교,본교,기존,사립,NaN,서울 서대문구 홍제3동 서울여자간호대학,NaN,서울특별시,서대문구,홍제2동,02-2287-1700,02-395-8018,http://www.snjc.ac.kr
2,BE_LiST23-0036,2013,일반대학,서울여자대학교,본교,기존,사립,NaN,서울특별시 노원구 화랑로 621 서울여자대학교,NaN,서울특별시,노원구,공릉2동,02-970-5114,02-978-7931,http://www.swu.ac.kr
3,BE_LiST23-0037,2013,전문대학(2년제),서일대학교,본교,학교명 변경,사립,NaN,서울 중랑구 서일대학길 22(면목동 49-3) 서일대학교,NaN,서울특별시,중랑구,면목제3.8동,02-490-7300,02-493-2576,http://www.seoil.ac.kr
4,BE_LiST23-0038,2013,일반대학,성공회대학교,본교,기존,사립,NaN,서울 구로구 항동 성공회대학교,NaN,서울특별시,구로구,오류2동,02-2610-4142,02-2610-4248,http://www.skhu.ac.kr
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,BE_LiST23-0029,2013,교육대학,서울교육대학교,본교,기존,국립,NaN,서울 서초구 서초중앙로 96(서초동 1650),NaN,서울특별시,서초구,서초1동,02-3475-2114,02-581-7711,http://www.snue.ac.kr
60,BE_LiST23-0030,2013,일반대학,서울기독대학교,본교,기존,사립,NaN,서울 은평구 갈현로 4길 26-2호,NaN,서울특별시,은평구,신사1동,02-380-2500,02-380-2535,http://www.scu.ac.kr
61,BE_LiST23-0031,2013,일반대학,서울대학교,본교,기존,국립대법인,NaN,서울 관악구 관악로 1 서울대학교,NaN,서울특별시,관악구,낙성대동,02-880-5114,02-885-5272,http://www.snu.ac.kr
62,BE_LiST23-0032,2013,사이버대학(대학),서울디지털대학교,본교,기존,사립,NaN,서울 마포구 도화동 560번지,NaN,서울특별시,마포구,도화동,02-1644-0982,02-2128-3006,http://www.sdu.ac.kr
63,BE_LiST23-0033,2013,사이버대학(대학),서울사이버대학교,본교,기존,사립,NaN,서울 강북구 솔매로49길 60(미아동 193-15) 서울사이버대학교,NaN,서울특별시,강북구,미아동,02-944-5000,02-980-2222,http://www.iscu.ac.kr

In [8]:
# 필요없는 컬럼 삭제
data.drop(['키값', '본분교', '우편번호', '전화번호', '팩스번호', '홈페이지'], axis=1, inplace=True)
data

,연도,학교종류,학교명,학교상태,설립,주소,도로명주소,행정시,행정구,행정동
0,2013,일반대학,서울시립대학교,기존,공립,서울 동대문구 서울시립대로 163 (전농동 90번지),NaN,서울특별시,동대문구,휘경2동
1,2013,전문대학(3년제),서울여자간호대학교,기존,사립,서울 서대문구 홍제3동 서울여자간호대학,NaN,서울특별시,서대문구,홍제2동
2,2013,일반대학,서울여자대학교,기존,사립,서울특별시 노원구 화랑로 621 서울여자대학교,NaN,서울특별시,노원구,공릉2동
3,2013,전문대학(2년제),서일대학교,학교명 변경,사립,서울 중랑구 서일대학길 22(면목동 49-3) 서일대학교,NaN,서울특별시,중랑구,면목제3.8동
4,2013,일반대학,성공회대학교,기존,사립,서울 구로구 항동 성공회대학교,NaN,서울특별시,구로구,오류2동
...,...,...,...,...,...,...,...,...,...,...
59,2013,교육대학,서울교육대학교,기존,국립,서울 서초구 서초중앙로 96(서초동 1650),NaN,서울특별시,서초구,서초1동
60,2013,일반대학,서울기독대학교,기존,사립,서울 은평구 갈현로 4길 26-2호,NaN,서울특별시,은평구,신사1동
61,2013,일반대학,서울대학교,기존,국립대법인,서울 관악구 관악로 1 서울대학교,NaN,서울특별시,관악구,낙성대동
62,2013,사이버대학(대학),서울디지털대학교,기존,사립,서울 마포구 도화동 560번지,NaN,서울특별시,마포구,도화동
63,2013,사이버대학(대학),서울사이버대학교,기존,사립,서울 강북구 솔매로49길 60(미아동 193-15) 서울사이버대학교,NaN,서울특별시,강북구,미아동

In [9]:
data.isna().sum()

연도        0
학교종류      0
학교명       0
학교상태      0
설립        0
주소        0
도로명주소    64
행정시       0
행정구       0
행정동       0
dtype: int64

In [10]:
# 도로명주소, 연도 삭제
data.drop(['도로명주소', '연도'], axis=1, inplace=True)
data

,학교종류,학교명,학교상태,설립,주소,행정시,행정구,행정동
0,일반대학,서울시립대학교,기존,공립,서울 동대문구 서울시립대로 163 (전농동 90번지),서울특별시,동대문구,휘경2동
1,전문대학(3년제),서울여자간호대학교,기존,사립,서울 서대문구 홍제3동 서울여자간호대학,서울특별시,서대문구,홍제2동
2,일반대학,서울여자대학교,기존,사립,서울특별시 노원구 화랑로 621 서울여자대학교,서울특별시,노원구,공릉2동
3,전문대학(2년제),서일대학교,학교명 변경,사립,서울 중랑구 서일대학길 22(면목동 49-3) 서일대학교,서울특별시,중랑구,면목제3.8동
4,일반대학,성공회대학교,기존,사립,서울 구로구 항동 성공회대학교,서울특별시,구로구,오류2동
...,...,...,...,...,...,...,...,...
59,교육대학,서울교육대학교,기존,국립,서울 서초구 서초중앙로 96(서초동 1650),서울특별시,서초구,서초1동
60,일반대학,서울기독대학교,기존,사립,서울 은평구 갈현로 4길 26-2호,서울특별시,은평구,신사1동
61,일반대학,서울대학교,기존,국립대법인,서울 관악구 관악로 1 서울대학교,서울특별시,관악구,낙성대동
62,사이버대학(대학),서울디지털대학교,기존,사립,서울 마포구 도화동 560번지,서울특별시,마포구,도화동
63,사이버대학(대학),서울사이버대학교,기존,사립,서울 강북구 솔매로49길 60(미아동 193-15) 서울사이버대학교,서울특별시,강북구,미아동

In [22]:
data['학교상태'].unique()

array(['기존', '학교명 변경', '폐교', '학제 변경'], dtype=object)

In [33]:
data[data['학교상태']=='폐교']

         학교종류        학교명 학교상태  설립                         주소    행정시  행정구   행정동
15  전문대학(3년제)    적십자간호대학   폐교  사립               서울 종로구 경교장길8  서울특별시  종로구   교남동
58       산업대학  서울과학기술대학교   폐교  국립  서울시 노원구 공릉로 232 서울과학기술대학교  서울특별시  노원구  공릉2동

In [44]:
# 폐교된 대학 삭제
idx = data[data['학교상태']=='폐교'].index
data.drop(idx, axis=0, inplace=True)
data.reset_index(drop=True, inplace=True)
data

,학교종류,학교명,학교상태,설립,주소,행정시,행정구,행정동
0,일반대학,서울시립대학교,기존,공립,서울 동대문구 서울시립대로 163 (전농동 90번지),서울특별시,동대문구,휘경2동
1,전문대학(3년제),서울여자간호대학교,기존,사립,서울 서대문구 홍제3동 서울여자간호대학,서울특별시,서대문구,홍제2동
2,일반대학,서울여자대학교,기존,사립,서울특별시 노원구 화랑로 621 서울여자대학교,서울특별시,노원구,공릉2동
3,전문대학(2년제),서일대학교,학교명 변경,사립,서울 중랑구 서일대학길 22(면목동 49-3) 서일대학교,서울특별시,중랑구,면목제3.8동
4,일반대학,성공회대학교,기존,사립,서울 구로구 항동 성공회대학교,서울특별시,구로구,오류2동
...,...,...,...,...,...,...,...,...
57,교육대학,서울교육대학교,기존,국립,서울 서초구 서초중앙로 96(서초동 1650),서울특별시,서초구,서초1동
58,일반대학,서울기독대학교,기존,사립,서울 은평구 갈현로 4길 26-2호,서울특별시,은평구,신사1동
59,일반대학,서울대학교,기존,국립대법인,서울 관악구 관악로 1 서울대학교,서울특별시,관악구,낙성대동
60,사이버대학(대학),서울디지털대학교,기존,사립,서울 마포구 도화동 560번지,서울특별시,마포구,도화동
61,사이버대학(대학),서울사이버대학교,기존,사립,서울 강북구 솔매로49길 60(미아동 193-15) 서울사이버대학교,서울특별시,강북구,미아동

In [45]:
# 학교상태 컬럼 삭제
data.drop('학교상태', axis=1, inplace=True)
data

,학교종류,학교명,설립,주소,행정시,행정구,행정동
0,일반대학,서울시립대학교,공립,서울 동대문구 서울시립대로 163 (전농동 90번지),서울특별시,동대문구,휘경2동
1,전문대학(3년제),서울여자간호대학교,사립,서울 서대문구 홍제3동 서울여자간호대학,서울특별시,서대문구,홍제2동
2,일반대학,서울여자대학교,사립,서울특별시 노원구 화랑로 621 서울여자대학교,서울특별시,노원구,공릉2동
3,전문대학(2년제),서일대학교,사립,서울 중랑구 서일대학길 22(면목동 49-3) 서일대학교,서울특별시,중랑구,면목제3.8동
4,일반대학,성공회대학교,사립,서울 구로구 항동 성공회대학교,서울특별시,구로구,오류2동
...,...,...,...,...,...,...,...
57,교육대학,서울교육대학교,국립,서울 서초구 서초중앙로 96(서초동 1650),서울특별시,서초구,서초1동
58,일반대학,서울기독대학교,사립,서울 은평구 갈현로 4길 26-2호,서울특별시,은평구,신사1동
59,일반대학,서울대학교,국립대법인,서울 관악구 관악로 1 서울대학교,서울특별시,관악구,낙성대동
60,사이버대학(대학),서울디지털대학교,사립,서울 마포구 도화동 560번지,서울특별시,마포구,도화동
61,사이버대학(대학),서울사이버대학교,사립,서울 강북구 솔매로49길 60(미아동 193-15) 서울사이버대학교,서울특별시,강북구,미아동

In [47]:
# 데이터 저장
data.to_csv('data/대학교(전처리, cp949).csv', encoding='cp949', index=False)

### 좌표추가 데이터 전처리

In [2]:
df = pd.read_csv('data/대학교(좌표추가, cp949).csv', encoding='cp949')
df

,No,학교종류,학교명,설립,주소,행정시,행정구,행정동,경도,위도,상태
0,1,일반대학,서울시립대학교,공립,서울 동대문구 서울시립대로 163 (전농동 90번지),서울특별시,동대문구,휘경2동,127.060864,37.583018,정좌표
1,2,일반대학,서울여자대학교,사립,서울특별시 노원구 화랑로 621 서울여자대학교,서울특별시,노원구,공릉2동,127.090476,37.629322,정좌표
2,3,일반대학,숙명여자대학교,사립,서울 용산구 청파로47길 100 숙명여자대학교,서울특별시,용산구,청파동,126.965768,37.545975,정좌표
3,4,일반대학,숭실대학교,사립,서울 동작구 상도동 511 숭실대학교,서울특별시,동작구,상도1동,126.957198,37.496344,정좌표
4,5,전문대학(2년제),숭의여자대학교,사립,서울특별시 중구 소파로2길 10(예장동),서울특별시,중구,필동,126.987229,37.556770,정좌표
...,...,...,...,...,...,...,...,...,...,...,...
57,58,전문대학(3년제),서울여자간호대학교,사립,서울특별시 서대문구 간호대로 38,서울특별시,서대문구,홍제2동,126.947757,37.597570,정좌표
58,59,전문대학(2년제),서일대학교,사립,서울특별시 중랑구 용마산로90길 28,서울특별시,중랑구,면목제3.8동,127.097199,37.586075,정좌표
59,60,일반대학,성공회대학교,사립,서울특별시 구로구 연동로 320,서울특별시,구로구,오류2동,126.825661,37.488119,정좌표
60,61,일반대학,그리스도대학교,사립,서울특별시 강서구 까치산로24길 47,서울특별시,강서구,화곡본동,126.854158,37.548687,정좌표
61,62,일반대학,동덕여자대학교,사립,서울특별시 성북구 화랑로13길 60,서울특별시,성북구,삼선동,127.044073,37.606701,정좌표

In [3]:
# 필요없는 컬럼 삭제
df.drop(['No', '상태'], axis=1, inplace=True)
df

,학교종류,학교명,설립,주소,행정시,행정구,행정동,경도,위도
0,일반대학,서울시립대학교,공립,서울 동대문구 서울시립대로 163 (전농동 90번지),서울특별시,동대문구,휘경2동,127.060864,37.583018
1,일반대학,서울여자대학교,사립,서울특별시 노원구 화랑로 621 서울여자대학교,서울특별시,노원구,공릉2동,127.090476,37.629322
2,일반대학,숙명여자대학교,사립,서울 용산구 청파로47길 100 숙명여자대학교,서울특별시,용산구,청파동,126.965768,37.545975
3,일반대학,숭실대학교,사립,서울 동작구 상도동 511 숭실대학교,서울특별시,동작구,상도1동,126.957198,37.496344
4,전문대학(2년제),숭의여자대학교,사립,서울특별시 중구 소파로2길 10(예장동),서울특별시,중구,필동,126.987229,37.556770
...,...,...,...,...,...,...,...,...,...
57,전문대학(3년제),서울여자간호대학교,사립,서울특별시 서대문구 간호대로 38,서울특별시,서대문구,홍제2동,126.947757,37.597570
58,전문대학(2년제),서일대학교,사립,서울특별시 중랑구 용마산로90길 28,서울특별시,중랑구,면목제3.8동,127.097199,37.586075
59,일반대학,성공회대학교,사립,서울특별시 구로구 연동로 320,서울특별시,구로구,오류2동,126.825661,37.488119
60,일반대학,그리스도대학교,사립,서울특별시 강서구 까치산로24길 47,서울특별시,강서구,화곡본동,126.854158,37.548687
61,일반대학,동덕여자대학교,사립,서울특별시 성북구 화랑로13길 60,서울특별시,성북구,삼선동,127.044073,37.606701

In [4]:
# 데이터 저장
df.to_csv('data/대학교(전처리 완료, cp949).csv', encoding='cp949', index=False)

### 학교 데이터 전체 병합

In [2]:
# 데이터 불러오기
pre_df1 = pd.read_csv('data/FIN/어린이집_유치원 2017-2019(전처리완료, cp949).csv', encoding='cp949')
pre_df2 = pd.read_csv('data/FIN/어린이집_유치원 2020(전처리완료, cp949).csv', encoding='cp949')
school_df1 = pd.read_csv('data/FIN/서울특별시 학교 데이터 2017-2019(전처리 완료, cp949).csv', encoding='cp949')
school_df2 = pd.read_csv('data/FIN/서울특별시 학교 데이터 2020(전처리 완료, cp949).csv', encoding='cp949')
univ_df = pd.read_csv('data/FIN/대학교(전처리 완료, cp949).csv', encoding='cp949')

In [3]:
# 필요없는 컬럼 삭제
pre_df1.drop(['인허가일자', '폐업일자'], axis=1, inplace=True)
pre_df2.drop(['인허가일자', '폐업일자'], axis=1, inplace=True)
school_df1.drop(['설립일자', '소재지도로명주소'], axis=1, inplace=True)
school_df2.drop(['설립일자', '소재지도로명주소'], axis=1, inplace=True)
univ_df.drop(['설립', '행정시', '행정구', '행정동'], axis=1, inplace=True)

In [4]:
pre_df1.isna().sum()

년          0
상세영업상태명    0
업태구분명      0
사업장명       0
주소         0
경도         0
위도         0
dtype: int64

In [5]:
school_df1.isna().sum()

년          0
업태구분명      0
학교명        0
소재지지번주소    0
위도         0
경도         0
dtype: int64

In [6]:
# 컬럼명 변경
pre_df1.rename({'업태구분명' : '학교종류', '사업장명' : '학교명'}, axis='columns', inplace=True)
pre_df2.rename({'업태구분명' : '학교종류', '사업장명' : '학교명'}, axis='columns', inplace=True)
school_df1.rename({'업태구분명' : '학교종류', '소재지지번주소' : '주소'}, axis='columns', inplace=True)
school_df2.rename({'업태구분명' : '학교종류', '소재지지번주소' : '주소'}, axis='columns', inplace=True)

In [7]:
pre_df1

,년,상세영업상태명,학교종류,학교명,주소,경도,위도
0,2017,영업,어린이집,개미어린이집,서울특별시 금천구 독산동 993-30번지 개미어린이집,126.905875,37.473026
1,2017,영업,어린이집,정심어린이집,서울특별시 금천구 독산동 938-5번지,126.907258,37.467753
2,2017,영업,어린이집,독산1동어린이집,서울특별시 금천구 독산동 999-11번지 독산1동어린이집,126.890859,37.468222
3,2017,영업,어린이집,새길어린이집,서울특별시 금천구 시흥동 산 13-8번지,126.907530,37.440138
4,2017,영업,어린이집,가산어린이집,서울특별시 금천구 가산동 602-71번지 가산어린이집상록경록당,126.884379,37.482694
...,...,...,...,...,...,...,...
9265,2019,영업,어린이집,지니어스어린이집,서울특별시 강서구 등촌동 637 서울시니어스가양타워(지상 1층),126.859228,37.556925
9266,2019,영업,어린이집,아트어린이집,서울특별시 성북구 상월곡동 62,127.044827,37.606058
9267,2019,영업,어린이집,구립 송파파크센트럴 어린이집,서울특별시 송파구 거여동 234 e편한세상 송파 파크센트럴,127.150589,37.493167
9268,2019,영업,어린이집,당산2동 은솔어린이집,서울특별시 영등포구 당산동5가 4-13,126.903069,37.530103
9269,2019,영업,어린이집,새솔아델포레어린이집,서울특별시 영등포구 대림동 917-49 e편한세상 영등포 아델포레,126.906905,37.494363

In [8]:
school_df1

         년  학교종류        학교명                      주소         위도          경도
0     2017  초등학교   서울휘경초등학교    서울특별시 동대문구 휘경동 302-2  37.585736  127.058213
1     2017  초등학교   서울동답초등학교    서울특별시 동대문구 답십리동 2-24  37.571503  127.064034
2     2017  초등학교  서울답십리초등학교     서울특별시 동대문구 답십리동 274  37.568804  127.055429
3     2017  초등학교   서울신답초등학교  서울특별시 동대문구 답십리동 463-13  37.572705  127.042962
4     2017  초등학교   서울용두초등학교    서울특별시 동대문구 용두동 237-1  37.576415  127.028387
...    ...   ...        ...                     ...        ...         ...
3903  2019  고등학교     도선고등학교  서울특별시 성동구 하왕십리동 1070-4  37.566843  127.026994
3904  2019  고등학교     환일고등학교     서울특별시 마포구 아현동 393-1  37.553868  126.962210
3905  2019  고등학교     계성고등학교   서울특별시 성북구 길음동 1284-15  37.607493  127.020181
3906  2019  고등학교   대일관광고등학교    서울특별시 양천구 신정동 1318-3  37.511413  126.834905
3907  2019  고등학교     풍문고등학교       서울특별시 강남구 자곡동 643  37.471360  127.099965

[3908 rows x 6 columns]

In [9]:
# school_df : 상세영업상태명 컬럼 추가
school_df1['상세영업상태명'] = '영업'
school_df2['상세영업상태명'] = '영업'

In [10]:
# univ_df : 상세영업상태명 컬럼 추가
univ_df['상세영업상태명']='영업'

# 2017~2020년 df 생성
univ_2017 = univ_df.copy()
univ_2018 = univ_df.copy()
univ_2019 = univ_df.copy()
univ_2020 = univ_df.copy()

In [11]:
# 년 컬럼 추가
univ_2017['년'] = 2017
univ_2018['년'] = 2018
univ_2019['년'] = 2019
univ_2020['년'] = 2020

In [12]:
# 2017~2019 df 병합, 컬럼 정렬
univ_2017_2019 = pd.concat([univ_2017, univ_2018, univ_2019], axis=0).reset_index(drop=True)
univ_2017_2019 = univ_2017_2019[['년', '상세영업상태명', '학교종류', '학교명', '주소', '위도', '경도']]

In [13]:
univ_2017_2019

,년,상세영업상태명,학교종류,학교명,주소,위도,경도
0,2017,영업,일반대학,서울시립대학교,서울 동대문구 서울시립대로 163 (전농동 90번지),37.583018,127.060864
1,2017,영업,일반대학,서울여자대학교,서울특별시 노원구 화랑로 621 서울여자대학교,37.629322,127.090476
2,2017,영업,일반대학,숙명여자대학교,서울 용산구 청파로47길 100 숙명여자대학교,37.545975,126.965768
3,2017,영업,일반대학,숭실대학교,서울 동작구 상도동 511 숭실대학교,37.496344,126.957198
4,2017,영업,전문대학(2년제),숭의여자대학교,서울특별시 중구 소파로2길 10(예장동),37.556770,126.987229
...,...,...,...,...,...,...,...
181,2019,영업,전문대학(3년제),서울여자간호대학교,서울특별시 서대문구 간호대로 38,37.597570,126.947757
182,2019,영업,전문대학(2년제),서일대학교,서울특별시 중랑구 용마산로90길 28,37.586075,127.097199
183,2019,영업,일반대학,성공회대학교,서울특별시 구로구 연동로 320,37.488119,126.825661
184,2019,영업,일반대학,그리스도대학교,서울특별시 강서구 까치산로24길 47,37.548687,126.854158
185,2019,영업,일반대학,동덕여자대학교,서울특별시 성북구 화랑로13길 60,37.606701,127.044073

In [14]:
# 학교 데이터 전체 병합
data = pd.concat([pre_df1, school_df1, univ_2017_2019], axis=0).reset_index(drop=True)
data2 = pd.concat([pre_df2, school_df2, univ_2020], axis=0).reset_index(drop=True)
data

,년,상세영업상태명,학교종류,학교명,주소,경도,위도
0,2017,영업,어린이집,개미어린이집,서울특별시 금천구 독산동 993-30번지 개미어린이집,126.905875,37.473026
1,2017,영업,어린이집,정심어린이집,서울특별시 금천구 독산동 938-5번지,126.907258,37.467753
2,2017,영업,어린이집,독산1동어린이집,서울특별시 금천구 독산동 999-11번지 독산1동어린이집,126.890859,37.468222
3,2017,영업,어린이집,새길어린이집,서울특별시 금천구 시흥동 산 13-8번지,126.907530,37.440138
4,2017,영업,어린이집,가산어린이집,서울특별시 금천구 가산동 602-71번지 가산어린이집상록경록당,126.884379,37.482694
...,...,...,...,...,...,...,...
13359,2019,영업,전문대학(3년제),서울여자간호대학교,서울특별시 서대문구 간호대로 38,126.947757,37.597570
13360,2019,영업,전문대학(2년제),서일대학교,서울특별시 중랑구 용마산로90길 28,127.097199,37.586075
13361,2019,영업,일반대학,성공회대학교,서울특별시 구로구 연동로 320,126.825661,37.488119
13362,2019,영업,일반대학,그리스도대학교,서울특별시 강서구 까치산로24길 47,126.854158,37.548687
13363,2019,영업,일반대학,동덕여자대학교,서울특별시 성북구 화랑로13길 60,127.044073,37.606701

In [15]:
# 년 기준 정렬
data.sort_values(by=['년'], axis=0, inplace=True)

In [16]:
data

,년,상세영업상태명,학교종류,학교명,주소,경도,위도
0,2017,영업,어린이집,개미어린이집,서울특별시 금천구 독산동 993-30번지 개미어린이집,126.905875,37.473026
2819,2017,영업,어린이집,숲속 어린이집,서울특별시 서대문구 홍제동 453번지,126.952024,37.581905
2820,2017,폐업,어린이집,구립역마을어린이집,서울특별시 은평구 역촌동 73-29번지,126.908485,37.604240
2821,2017,영업,어린이집,금융감독원어린이집,서울특별시 영등포구 여의도동 27번지 1층,126.921306,37.523047
2822,2017,영업,어린이집,구립 밝은어린이집,서울특별시 구로구 가리봉동 2-10번지,126.882492,37.486374
...,...,...,...,...,...,...,...
8228,2019,영업,어린이집,행복숲 어린이집,서울특별시 송파구 가락동 181-22번지,127.135395,37.494479
8227,2019,영업,어린이집,산마루 어린이집,서울특별시 서대문구 북아현동 1-595번지,126.951117,37.565710
8226,2019,영업,어린이집,한울어린이집,서울특별시 관악구 남현동 산 100-14번지,126.981722,37.461543
8248,2019,영업,어린이집,은혜감사어린이집,서울특별시 서대문구 남가좌동 5-7번지,126.922693,37.582012
13363,2019,영업,일반대학,동덕여자대학교,서울특별시 성북구 화랑로13길 60,127.044073,37.606701

In [17]:
# 데이터 저장
data.to_csv('data/FIN/학교 2017-2019(전처리 완료, cp949).csv', encoding='cp949', index=False)
data2.to_csv('data/FIN/학교 2020(전처리 완료, cp949).csv', encoding='cp949', index=False)