In [1]:
import numpy as np
import pandas as pd
from datetime import timedelta
import glob
import os

import warnings
warnings.filterwarnings(action='ignore')

### 1. 필요한 컬럼 추출

In [33]:
file = pd.read_csv('raw/서울특별시 영화상영관 인허가 정보.csv', encoding='cp949')
file

,개방자치단체코드,관리번호,인허가일자,인허가취소일자,영업상태코드,영업상태명,상세영업상태코드,상세영업상태명,폐업일자,휴업시작일자,...,음향시설여부,편의시설여부,소방시설여부,총게임기수,기존게임업외업종명,제공게임물명,공연장형태구분명,품목명,최초등록시점,지역구분명
0,3000000,CDFF4220002003000009,20030212,NaN,1,영업/정상,13,영업중,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,영화관,NaN,20030212.0,NaN
1,3000000,CDFF4220002003000008,20030212,NaN,1,영업/정상,13,영업중,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,영화관,NaN,20030212.0,NaN
2,3000000,CDFF4220002003000007,20030212,NaN,1,영업/정상,13,영업중,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,영화관,NaN,20030212.0,NaN
3,3000000,CDFF4220002003000027,20030212,NaN,3,폐업,03,폐업,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,영화관,NaN,20030212.0,NaN
4,3000000,CDFF4220002003000026,20030212,NaN,3,폐업,03,폐업,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,영화관,NaN,20030212.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
854,3130000,CDFF4220002012000004,20120718,NaN,1,영업/정상,13,영업중,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
855,3130000,CDFF4220002007000001,20070906,NaN,1,영업/정상,13,영업중,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
856,3160000,CDFF4220002005000001,20050310,NaN,1,영업/정상,13,영업중,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
857,3160000,CDFF4220001999000002,19990227,NaN,1,영업/정상,13,영업중,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
858,3010000,CDFF4220002012000001,20120723,NaN,3,폐업,03,폐업,20200916.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
# Nan값 확인
file.isnull().sum()

개방자치단체코드       0
관리번호           0
인허가일자          0
인허가취소일자      859
영업상태코드         0
영업상태명          0
상세영업상태코드       0
상세영업상태명       14
폐업일자         660
휴업시작일자       859
휴업종료일자       859
재개업일자        859
전화번호         281
소재지면적        859
소재지우편번호      639
지번주소           0
도로명주소         35
도로명우편번호      389
사업장명           0
최종수정일자         0
데이터갱신구분        0
데이터갱신일자        0
업태구분명        859
좌표정보(X)        7
좌표정보(Y)        7
문화체육업종명       25
문화사업자구분명     296
총층수          469
주변환경명        640
제작취급품목내용     859
시설면적         786
지상층수         306
지하층수         352
건물용도명        468
통로너비         783
조명시설조도       859
노래방실수        859
청소년실수        859
비상계단여부       859
비상구여부        859
자동환기여부       859
청소년실여부       859
특수조명여부       859
방음시설여부       859
비디오재생기명      859
조명시설유무       859
음향시설여부       859
편의시설여부       859
소방시설여부       859
총게임기수        859
기존게임업외업종명    859
제공게임물명       859
공연장형태구분명      73
품목명          859
최초등록시점        25
지역구분명        554
dtype: int64

In [35]:
# 필요한 컬럼만 빼서 저장하기
## 상세영업상태명, 폐업일자, 지번주소, 사업장명, 최종수정일자, 공연장형태구분명, 최초등록시점

df = file[['상세영업상태명', '폐업일자', '지번주소', '사업장명', '최종수정일자', '공연장형태구분명', '최초등록시점']]
df

,상세영업상태명,폐업일자,지번주소,사업장명,최종수정일자,공연장형태구분명,최초등록시점
0,영업중,NaN,서울특별시 종로구 관수동 59-7번지 5층,서울극장 5관,20180104094949,영화관,20030212.0
1,영업중,NaN,서울특별시 종로구 관수동 59-7번지 지하1층,서울극장 3관,20180104094911,영화관,20030212.0
2,영업중,NaN,서울특별시 종로구 관수동 59-7번지 2층 3중?상층,서울극장 2관,20180104094746,영화관,20030212.0
3,폐업,NaN,서울특별시 종로구 명륜4가 113-1번지,씨네유극장 4관,20090414134958,영화관,20030212.0
4,폐업,NaN,서울특별시 종로구 명륜4가 113-1번지,씨네유극장 3관,20090414134921,영화관,20030212.0
...,...,...,...,...,...,...,...
854,영업중,NaN,서울특별시 마포구 서교동 490 메세나폴리스 2층,롯데시네마 합정 제4관,20200805104930,NaN,NaN
855,영업중,NaN,서울특별시 마포구 서교동 367-5,시네마 상상마당,20200805112800,NaN,NaN
856,영업중,NaN,서울특별시 구로구 구로동 102번지,구로문화원,20200820165810,NaN,NaN
857,영업중,NaN,서울특별시 구로구 개봉동 339-9번지,샘물,20200820165701,NaN,NaN
858,폐업,20200916.0,서울특별시 중구 황학동 2545,롯데시네마 황학(제1관),20200917091427,NaN,NaN

In [36]:
df.isnull().sum()

상세영업상태명      14
폐업일자        660
지번주소          0
사업장명          0
최종수정일자        0
공연장형태구분명     73
최초등록시점       25
dtype: int64

In [37]:
# 컬럼 타입 확인
df.dtypes

상세영업상태명      object
폐업일자        float64
지번주소         object
사업장명         object
최종수정일자        int64
공연장형태구분명     object
최초등록시점      float64
dtype: object

### 2. NaN 전처리
#### 1) 상세영업상태명

In [38]:
# 상세영업상태명 Nan값 처리 : 삭제
## 주소와 사업자명만 다른 동일 장소가 이미 존재
df = df[df['상세영업상태명'].notnull()].reset_index(drop=True)
df

,상세영업상태명,폐업일자,지번주소,사업장명,최종수정일자,공연장형태구분명,최초등록시점
0,영업중,NaN,서울특별시 종로구 관수동 59-7번지 5층,서울극장 5관,20180104094949,영화관,20030212.0
1,영업중,NaN,서울특별시 종로구 관수동 59-7번지 지하1층,서울극장 3관,20180104094911,영화관,20030212.0
2,영업중,NaN,서울특별시 종로구 관수동 59-7번지 2층 3중?상층,서울극장 2관,20180104094746,영화관,20030212.0
3,폐업,NaN,서울특별시 종로구 명륜4가 113-1번지,씨네유극장 4관,20090414134958,영화관,20030212.0
4,폐업,NaN,서울특별시 종로구 명륜4가 113-1번지,씨네유극장 3관,20090414134921,영화관,20030212.0
...,...,...,...,...,...,...,...
840,영업중,NaN,서울특별시 마포구 서교동 490 메세나폴리스 2층,롯데시네마 합정 제4관,20200805104930,NaN,NaN
841,영업중,NaN,서울특별시 마포구 서교동 367-5,시네마 상상마당,20200805112800,NaN,NaN
842,영업중,NaN,서울특별시 구로구 구로동 102번지,구로문화원,20200820165810,NaN,NaN
843,영업중,NaN,서울특별시 구로구 개봉동 339-9번지,샘물,20200820165701,NaN,NaN
844,폐업,20200916.0,서울특별시 중구 황학동 2545,롯데시네마 황학(제1관),20200917091427,NaN,NaN

In [39]:
df.isnull().sum()

상세영업상태명       0
폐업일자        646
지번주소          0
사업장명          0
최종수정일자        0
공연장형태구분명     59
최초등록시점       25
dtype: int64

#### 2. 폐업일자 NaN값 처리

In [40]:
# 컬럼 타입 변환 : 폐업일자에 맞추기
df['최종수정일자'] = df['최종수정일자'].astype(float)

In [41]:
df.dtypes

상세영업상태명      object
폐업일자        float64
지번주소         object
사업장명         object
최종수정일자      float64
공연장형태구분명     object
최초등록시점      float64
dtype: object

In [42]:
# df 분리
## open_null_df : 영업중이고 폐업일자가 null인 영화관
## closed_null_df : 영업 종료했고 폐업일자가 null인 영화관
## notnull_df : 폐업일자가 null이 아닌 영화관

open_null_df = df[(df['상세영업상태명']=='영업중')&(df['폐업일자'].isna())].reset_index(drop=True)
closed_null_df = df[(df['상세영업상태명']!='영업중')&(df['폐업일자'].isna())].reset_index(drop=True)
notnull_df = df[df['폐업일자'].notnull()].reset_index(drop=True)
notnull_df['최종수정일자'] = notnull_df['최종수정일자'].astype('int64')
print(len(open_null_df), len(closed_null_df), len(notnull_df))

634 12 199

In [43]:
# 영업 종료했고 폐업일자가 null인 영화관의 폐업일자를 데이터 최종수정일자로 채우기
closed_null_list = (closed_null_df['최종수정일자']//1000000).values.tolist()
closed_null_list

[20090414.0,
 20090414.0,
 20110516.0,
 20090414.0,
 20090414.0,
 20140403.0,
 20090414.0,
 20180118.0,
 20090408.0,
 20150821.0,
 20150513.0,
 20150513.0]

In [44]:
closed_null_df['폐업일자'] = closed_null_list
closed_null_df['최종수정일자'] = closed_null_df['최종수정일자'].astype('int64')
closed_null_df

,상세영업상태명,폐업일자,지번주소,사업장명,최종수정일자,공연장형태구분명,최초등록시점
0,폐업,20090414.0,서울특별시 종로구 명륜4가 113-1번지,씨네유극장 4관,20090414134958,영화관,20030212.0
1,폐업,20090414.0,서울특별시 종로구 명륜4가 113-1번지,씨네유극장 3관,20090414134921,영화관,20030212.0
2,폐업,20110516.0,서울특별시 종로구 신문로2가 1-153번지 2층,독립영화전용관 시네마루,20110516090539,영화관,20100415.0
3,폐업,20090414.0,서울특별시 종로구 명륜4가 113-1번지,씨네유극장 2관,20090414134932,영화관,20030212.0
4,폐업,20090414.0,서울특별시 종로구 명륜4가 113-1번지,씨네유극장 1관,20090414134947,영화관,20030212.0
5,폐업,20140403.0,서울특별시 종로구 관수동 59-7번지 4층 5중?상층,서울극장 1관,20140403190559,영화관,20030212.0
6,폐업,20090414.0,서울특별시 종로구 명륜4가 113-1번지,씨네유극장 5관,20090414135009,영화관,20030212.0
7,폐업,20180118.0,서울특별시 강서구 방화동 886번지,CGV김포공항9 (3관),20180118144704,영화관,20030122.0
8,폐업,20090408.0,서울특별시 은평구 불광동 31-2번지,객석시네마,20090408132446,영화관,20000107.0
9,폐업,20150821.0,서울특별시 영등포구 여의도동 60-0번지,63아이맥스영화관,20150821155203,영화관,19830730.0
10,지정취소,20150513.0,서울특별시 강남구 역삼동 814-6번지,동아극장 1관,20150513132011,영화관,19830604.0
11,지정취소,20150513.0,서울특별시 강남구 역삼동 814-6번지,동아극장 3관,20150513132219,영화관,19941223.0

In [45]:
# 영업중이고 폐업일자가 null인 영화관의 폐업일자를 0.0으로 채우기
open_null_df['폐업일자'].fillna(0.0, inplace=True)
open_null_df['최종수정일자'] = open_null_df['최종수정일자'].astype('int64')
open_null_df

,상세영업상태명,폐업일자,지번주소,사업장명,최종수정일자,공연장형태구분명,최초등록시점
0,영업중,0.0,서울특별시 종로구 관수동 59-7번지 5층,서울극장 5관,20180104094949,영화관,20030212.0
1,영업중,0.0,서울특별시 종로구 관수동 59-7번지 지하1층,서울극장 3관,20180104094911,영화관,20030212.0
2,영업중,0.0,서울특별시 종로구 관수동 59-7번지 2층 3중?상층,서울극장 2관,20180104094746,영화관,20030212.0
3,영업중,0.0,서울특별시 종로구 관수동 59-7번지 3층,서울아트시네마,20150423180214,영화관,20030802.0
4,영업중,0.0,서울특별시 종로구 관수동 59-7번지 5층,서울극장 10관,20180104095240,영화관,20030802.0
...,...,...,...,...,...,...,...
629,영업중,0.0,서울특별시 강남구 삼성동 159,코엑스 Dolby Cinema,20200717101740,NaN,NaN
630,영업중,0.0,서울특별시 마포구 서교동 490 메세나폴리스 2층,롯데시네마 합정 제4관,20200805104930,NaN,NaN
631,영업중,0.0,서울특별시 마포구 서교동 367-5,시네마 상상마당,20200805112800,NaN,NaN
632,영업중,0.0,서울특별시 구로구 구로동 102번지,구로문화원,20200820165810,NaN,NaN
633,영업중,0.0,서울특별시 구로구 개봉동 339-9번지,샘물,20200820165701,NaN,NaN

In [46]:
# 세 df 합치기
result_df = pd.concat([open_null_df, closed_null_df, notnull_df], axis=0).reset_index(drop=True)
result_df

,상세영업상태명,폐업일자,지번주소,사업장명,최종수정일자,공연장형태구분명,최초등록시점
0,영업중,0.0,서울특별시 종로구 관수동 59-7번지 5층,서울극장 5관,20180104094949,영화관,20030212.0
1,영업중,0.0,서울특별시 종로구 관수동 59-7번지 지하1층,서울극장 3관,20180104094911,영화관,20030212.0
2,영업중,0.0,서울특별시 종로구 관수동 59-7번지 2층 3중?상층,서울극장 2관,20180104094746,영화관,20030212.0
3,영업중,0.0,서울특별시 종로구 관수동 59-7번지 3층,서울아트시네마,20150423180214,영화관,20030802.0
4,영업중,0.0,서울특별시 종로구 관수동 59-7번지 5층,서울극장 10관,20180104095240,영화관,20030802.0
...,...,...,...,...,...,...,...
840,폐업,20090723.0,서울특별시 강동구 암사동 501-9번지 반달길 65,암사시네마 1관,20090724094753,영화관,20080918.0
841,폐업,20101101.0,서울특별시 강동구 성내동 48-1번지,한일시네마 5관,20101105160225,영화관,20000616.0
842,폐업,20101101.0,서울특별시 강동구 성내동 48-1번지,한일시네마 3관,20101105160153,영화관,20000616.0
843,폐업,20200916.0,서울특별시 중구 황학동 2545,롯데시네마 황학(제2관),20200917091457,NaN,NaN
844,폐업,20200916.0,서울특별시 중구 황학동 2545,롯데시네마 황학(제1관),20200917091427,NaN,NaN

In [47]:
# 컬럼 타입 변환 : 폐업일자를 int64로 변환
result_df = result_df.astype({'폐업일자' : 'int64'})
result_df

,상세영업상태명,폐업일자,지번주소,사업장명,최종수정일자,공연장형태구분명,최초등록시점
0,영업중,0,서울특별시 종로구 관수동 59-7번지 5층,서울극장 5관,20180104094949,영화관,20030212.0
1,영업중,0,서울특별시 종로구 관수동 59-7번지 지하1층,서울극장 3관,20180104094911,영화관,20030212.0
2,영업중,0,서울특별시 종로구 관수동 59-7번지 2층 3중?상층,서울극장 2관,20180104094746,영화관,20030212.0
3,영업중,0,서울특별시 종로구 관수동 59-7번지 3층,서울아트시네마,20150423180214,영화관,20030802.0
4,영업중,0,서울특별시 종로구 관수동 59-7번지 5층,서울극장 10관,20180104095240,영화관,20030802.0
...,...,...,...,...,...,...,...
840,폐업,20090723,서울특별시 강동구 암사동 501-9번지 반달길 65,암사시네마 1관,20090724094753,영화관,20080918.0
841,폐업,20101101,서울특별시 강동구 성내동 48-1번지,한일시네마 5관,20101105160225,영화관,20000616.0
842,폐업,20101101,서울특별시 강동구 성내동 48-1번지,한일시네마 3관,20101105160153,영화관,20000616.0
843,폐업,20200916,서울특별시 중구 황학동 2545,롯데시네마 황학(제2관),20200917091457,NaN,NaN
844,폐업,20200916,서울특별시 중구 황학동 2545,롯데시네마 황학(제1관),20200917091427,NaN,NaN

In [48]:
result_df.dtypes

상세영업상태명      object
폐업일자          int64
지번주소         object
사업장명         object
최종수정일자        int64
공연장형태구분명     object
최초등록시점      float64
dtype: object

In [49]:
result_df.isna().sum()

상세영업상태명      0
폐업일자         0
지번주소         0
사업장명         0
최종수정일자       0
공연장형태구분명    59
최초등록시점      25
dtype: int64

#### 3) 최초등록시점 NaN 처리

In [50]:
# NaN값 0으로 처리
result_df['최초등록시점'].fillna(0.0, inplace=True)

# 데이터 타입 변환(int64)
result_df['최초등록시점'] = result_df['최초등록시점'].astype('int64')
result_df

,상세영업상태명,폐업일자,지번주소,사업장명,최종수정일자,공연장형태구분명,최초등록시점
0,영업중,0,서울특별시 종로구 관수동 59-7번지 5층,서울극장 5관,20180104094949,영화관,20030212
1,영업중,0,서울특별시 종로구 관수동 59-7번지 지하1층,서울극장 3관,20180104094911,영화관,20030212
2,영업중,0,서울특별시 종로구 관수동 59-7번지 2층 3중?상층,서울극장 2관,20180104094746,영화관,20030212
3,영업중,0,서울특별시 종로구 관수동 59-7번지 3층,서울아트시네마,20150423180214,영화관,20030802
4,영업중,0,서울특별시 종로구 관수동 59-7번지 5층,서울극장 10관,20180104095240,영화관,20030802
...,...,...,...,...,...,...,...
840,폐업,20090723,서울특별시 강동구 암사동 501-9번지 반달길 65,암사시네마 1관,20090724094753,영화관,20080918
841,폐업,20101101,서울특별시 강동구 성내동 48-1번지,한일시네마 5관,20101105160225,영화관,20000616
842,폐업,20101101,서울특별시 강동구 성내동 48-1번지,한일시네마 3관,20101105160153,영화관,20000616
843,폐업,20200916,서울특별시 중구 황학동 2545,롯데시네마 황학(제2관),20200917091457,NaN,0
844,폐업,20200916,서울특별시 중구 황학동 2545,롯데시네마 황학(제1관),20200917091427,NaN,0

In [51]:
result_df.isna().sum()

상세영업상태명      0
폐업일자         0
지번주소         0
사업장명         0
최종수정일자       0
공연장형태구분명    59
최초등록시점       0
dtype: int64

#### 4) 공연장형태구분명

In [52]:
result_df['공연장형태구분명'].fillna('영화관', inplace=True)
result_df

,상세영업상태명,폐업일자,지번주소,사업장명,최종수정일자,공연장형태구분명,최초등록시점
0,영업중,0,서울특별시 종로구 관수동 59-7번지 5층,서울극장 5관,20180104094949,영화관,20030212
1,영업중,0,서울특별시 종로구 관수동 59-7번지 지하1층,서울극장 3관,20180104094911,영화관,20030212
2,영업중,0,서울특별시 종로구 관수동 59-7번지 2층 3중?상층,서울극장 2관,20180104094746,영화관,20030212
3,영업중,0,서울특별시 종로구 관수동 59-7번지 3층,서울아트시네마,20150423180214,영화관,20030802
4,영업중,0,서울특별시 종로구 관수동 59-7번지 5층,서울극장 10관,20180104095240,영화관,20030802
...,...,...,...,...,...,...,...
840,폐업,20090723,서울특별시 강동구 암사동 501-9번지 반달길 65,암사시네마 1관,20090724094753,영화관,20080918
841,폐업,20101101,서울특별시 강동구 성내동 48-1번지,한일시네마 5관,20101105160225,영화관,20000616
842,폐업,20101101,서울특별시 강동구 성내동 48-1번지,한일시네마 3관,20101105160153,영화관,20000616
843,폐업,20200916,서울특별시 중구 황학동 2545,롯데시네마 황학(제2관),20200917091457,영화관,0
844,폐업,20200916,서울특별시 중구 황학동 2545,롯데시네마 황학(제1관),20200917091427,영화관,0

In [53]:
result_df.isna().sum()

상세영업상태명     0
폐업일자        0
지번주소        0
사업장명        0
최종수정일자      0
공연장형태구분명    0
최초등록시점      0
dtype: int64

### 3. row 제거
#### 1) 자동차 극장 데이터 삭제

In [58]:
car_theater = result_df[result_df['공연장형태구분명']=='자동차극장'].index
fin_df = result_df.drop(car_theater)
fin_df

,상세영업상태명,폐업일자,지번주소,사업장명,최종수정일자,공연장형태구분명,최초등록시점
0,영업중,0,서울특별시 종로구 관수동 59-7번지 5층,서울극장 5관,20180104094949,영화관,20030212
1,영업중,0,서울특별시 종로구 관수동 59-7번지 지하1층,서울극장 3관,20180104094911,영화관,20030212
2,영업중,0,서울특별시 종로구 관수동 59-7번지 2층 3중?상층,서울극장 2관,20180104094746,영화관,20030212
3,영업중,0,서울특별시 종로구 관수동 59-7번지 3층,서울아트시네마,20150423180214,영화관,20030802
4,영업중,0,서울특별시 종로구 관수동 59-7번지 5층,서울극장 10관,20180104095240,영화관,20030802
...,...,...,...,...,...,...,...
840,폐업,20090723,서울특별시 강동구 암사동 501-9번지 반달길 65,암사시네마 1관,20090724094753,영화관,20080918
841,폐업,20101101,서울특별시 강동구 성내동 48-1번지,한일시네마 5관,20101105160225,영화관,20000616
842,폐업,20101101,서울특별시 강동구 성내동 48-1번지,한일시네마 3관,20101105160153,영화관,20000616
843,폐업,20200916,서울특별시 중구 황학동 2545,롯데시네마 황학(제2관),20200917091457,영화관,0
844,폐업,20200916,서울특별시 중구 황학동 2545,롯데시네마 황학(제1관),20200917091427,영화관,0

#### 2) 폐업일자가 2017년 이전인 데이터 삭제

In [60]:
before_2017 = fin_df[(fin_df['폐업일자']!=0)&(fin_df['폐업일자']<=20170101)].reset_index(drop=True)
after_2017 = fin_df[(fin_df['폐업일자']==0)|(fin_df['폐업일자']>20170101)].reset_index(drop=True)
print(len(before_2015), len(after_2015))

180 661

### 4. 데이터 분리 및 저장

In [61]:
before_2017.to_csv('data/2016 이전/서울특별시 영화상영관 인허가 정보(~2016, cp949).csv', encoding='cp949', index=False)
after_2017.to_csv('data/서울특별시 영화상영관 인허가 정보(2017~2019, cp949).csv', encoding='cp949', index=False)

### 5. 2017년 이후 데이터 전처리
#### 1) 컬럼명 변경

In [34]:
data = pd.read_csv('data/영화관/서울특별시 영화상영관 인허가 정보(2017~2019, cp949).csv', encoding='cp949')
data

,상세영업상태명,폐업일자,지번주소,사업장명,최종수정일자,공연장형태구분명,최초등록시점
0,영업중,0,서울특별시 종로구 관수동 59-7번지 5층,서울극장 5관,20180104094949,영화관,20030212
1,영업중,0,서울특별시 종로구 관수동 59-7번지 지하1층,서울극장 3관,20180104094911,영화관,20030212
2,영업중,0,서울특별시 종로구 관수동 59-7번지 2층 3중?상층,서울극장 2관,20180104094746,영화관,20030212
3,영업중,0,서울특별시 종로구 관수동 59-7번지 3층,서울아트시네마,20150423180214,영화관,20030802
4,영업중,0,서울특별시 종로구 관수동 59-7번지 5층,서울극장 10관,20180104095240,영화관,20030802
...,...,...,...,...,...,...,...
650,폐업,20180118,서울특별시 강서구 방화동 886번지,CGV 김포공항9 (1관),20180118144613,영화관,20030122
651,폐업,20180118,서울특별시 강서구 방화동 886번지,CGV김포공항9 (8관),20180118145427,영화관,20030122
652,폐업,20170426,서울특별시 강남구 역삼동 679-1번지,LG아트센터,20170426165458,영화관,19991206
653,폐업,20200916,서울특별시 중구 황학동 2545,롯데시네마 황학(제2관),20200917091457,영화관,0
654,폐업,20200916,서울특별시 중구 황학동 2545,롯데시네마 황학(제1관),20200917091427,영화관,0

In [35]:
data.isna().sum()

상세영업상태명     0
폐업일자        0
지번주소        0
사업장명        0
최종수정일자      0
공연장형태구분명    0
최초등록시점      0
dtype: int64

In [36]:
data = data.rename({'최초등록시점' : '설립일자'}, axis=1)
data

,상세영업상태명,폐업일자,지번주소,사업장명,최종수정일자,공연장형태구분명,설립일자
0,영업중,0,서울특별시 종로구 관수동 59-7번지 5층,서울극장 5관,20180104094949,영화관,20030212
1,영업중,0,서울특별시 종로구 관수동 59-7번지 지하1층,서울극장 3관,20180104094911,영화관,20030212
2,영업중,0,서울특별시 종로구 관수동 59-7번지 2층 3중?상층,서울극장 2관,20180104094746,영화관,20030212
3,영업중,0,서울특별시 종로구 관수동 59-7번지 3층,서울아트시네마,20150423180214,영화관,20030802
4,영업중,0,서울특별시 종로구 관수동 59-7번지 5층,서울극장 10관,20180104095240,영화관,20030802
...,...,...,...,...,...,...,...
650,폐업,20180118,서울특별시 강서구 방화동 886번지,CGV 김포공항9 (1관),20180118144613,영화관,20030122
651,폐업,20180118,서울특별시 강서구 방화동 886번지,CGV김포공항9 (8관),20180118145427,영화관,20030122
652,폐업,20170426,서울특별시 강남구 역삼동 679-1번지,LG아트센터,20170426165458,영화관,19991206
653,폐업,20200916,서울특별시 중구 황학동 2545,롯데시네마 황학(제2관),20200917091457,영화관,0
654,폐업,20200916,서울특별시 중구 황학동 2545,롯데시네마 황학(제1관),20200917091427,영화관,0

#### 2) 같은 영화관 row 합치기

In [39]:
# 설립일자 기준 내림차순
data.sort_values(by=['설립일자'], axis=0, inplace=True)
data

,상세영업상태명,폐업일자,지번주소,사업장명,최종수정일자,공연장형태구분명,설립일자
654,폐업,20200916,서울특별시 중구 황학동 2545,롯데시네마 황학(제1관),20200917091427,영화관,0
653,폐업,20200916,서울특별시 중구 황학동 2545,롯데시네마 황학(제2관),20200917091457,영화관,0
327,영업중,0,서울특별시 마포구 동교동 159-8,CGV홍대 3관,20200827122024,영화관,0
631,영업중,0,서울특별시 구로구 개봉동 339-9번지,샘물,20200820165701,영화관,0
619,영업중,0,서울특별시 마포구 성산동 515번지 월드컵쇼핑몰내 1층,메가박스중앙(주) 상암월드컵경기장지점 MX관,20200623141135,영화관,0
...,...,...,...,...,...,...,...
126,영업중,0,서울특별시 성동구 성수동1가 656-335번지,메가박스중앙(주) 성수지점 더부티크 102호,20191213163233,영화관,20191106
130,영업중,0,서울특별시 성동구 성수동1가 656-335번지,메가박스중앙(주) 성수지점 MX관,20191213162857,영화관,20191106
131,영업중,0,서울특별시 성동구 성수동1가 656-335번지,메가박스중앙(주) 성수지점 2관,20191213162807,영화관,20191106
127,영업중,0,서울특별시 성동구 성수동1가 656-335번지,메가박스중앙(주) 성수지점 더부티크 101호,20191213163035,영화관,20191106
128,영업중,0,서울특별시 성동구 성수동1가 656-335번지,메가박스중앙(주) 성수지점 5관,20191213162959,영화관,20191106

In [40]:
# 지번주소 분리 : 시, 구, 동, 번지, 건물
data['시'] = data.지번주소.str.split(' ').str[0]
data['구'] = data.지번주소.str.split(' ').str[1]
data['동'] = data.지번주소.str.split(' ').str[2]
data['번지'] = data.지번주소.str.split(' ').str[3]
data['건물'] = data.지번주소.str.split(' ').str[4:]
data

,상세영업상태명,폐업일자,지번주소,사업장명,최종수정일자,공연장형태구분명,설립일자,시,구,동,번지,건물
654,폐업,20200916,서울특별시 중구 황학동 2545,롯데시네마 황학(제1관),20200917091427,영화관,0,서울특별시,중구,황학동,2545,[]
653,폐업,20200916,서울특별시 중구 황학동 2545,롯데시네마 황학(제2관),20200917091457,영화관,0,서울특별시,중구,황학동,2545,[]
327,영업중,0,서울특별시 마포구 동교동 159-8,CGV홍대 3관,20200827122024,영화관,0,서울특별시,마포구,동교동,159-8,[]
631,영업중,0,서울특별시 구로구 개봉동 339-9번지,샘물,20200820165701,영화관,0,서울특별시,구로구,개봉동,339-9번지,[]
619,영업중,0,서울특별시 마포구 성산동 515번지 월드컵쇼핑몰내 1층,메가박스중앙(주) 상암월드컵경기장지점 MX관,20200623141135,영화관,0,서울특별시,마포구,성산동,515번지,"[월드컵쇼핑몰내, 1층]"
...,...,...,...,...,...,...,...,...,...,...,...,...
126,영업중,0,서울특별시 성동구 성수동1가 656-335번지,메가박스중앙(주) 성수지점 더부티크 102호,20191213163233,영화관,20191106,서울특별시,성동구,성수동1가,656-335번지,[]
130,영업중,0,서울특별시 성동구 성수동1가 656-335번지,메가박스중앙(주) 성수지점 MX관,20191213162857,영화관,20191106,서울특별시,성동구,성수동1가,656-335번지,[]
131,영업중,0,서울특별시 성동구 성수동1가 656-335번지,메가박스중앙(주) 성수지점 2관,20191213162807,영화관,20191106,서울특별시,성동구,성수동1가,656-335번지,[]
127,영업중,0,서울특별시 성동구 성수동1가 656-335번지,메가박스중앙(주) 성수지점 더부티크 101호,20191213163035,영화관,20191106,서울특별시,성동구,성수동1가,656-335번지,[]
128,영업중,0,서울특별시 성동구 성수동1가 656-335번지,메가박스중앙(주) 성수지점 5관,20191213162959,영화관,20191106,서울특별시,성동구,성수동1가,656-335번지,[]

In [41]:
# 사업장명 분리 : 극장, 관
data.loc[:, "new_사업장명"] = data["사업장명"].str.replace('\(|\)|1관|2관|3관|4관|5관|6관|7관|8관|9관|10관|11관|12관|제|주식회사|<<|>>|125관', " ").str.strip()
data['극장'] = data.new_사업장명.str.split(' ').str[0]
data['관'] = data.new_사업장명.str.split(' ').str[1:]
data

,상세영업상태명,폐업일자,지번주소,사업장명,최종수정일자,공연장형태구분명,설립일자,시,구,동,번지,건물,new_사업장명,극장,관
654,폐업,20200916,서울특별시 중구 황학동 2545,롯데시네마 황학(제1관),20200917091427,영화관,0,서울특별시,중구,황학동,2545,[],롯데시네마 황학,롯데시네마,[황학]
653,폐업,20200916,서울특별시 중구 황학동 2545,롯데시네마 황학(제2관),20200917091457,영화관,0,서울특별시,중구,황학동,2545,[],롯데시네마 황학,롯데시네마,[황학]
327,영업중,0,서울특별시 마포구 동교동 159-8,CGV홍대 3관,20200827122024,영화관,0,서울특별시,마포구,동교동,159-8,[],CGV홍대,CGV홍대,[]
631,영업중,0,서울특별시 구로구 개봉동 339-9번지,샘물,20200820165701,영화관,0,서울특별시,구로구,개봉동,339-9번지,[],샘물,샘물,[]
619,영업중,0,서울특별시 마포구 성산동 515번지 월드컵쇼핑몰내 1층,메가박스중앙(주) 상암월드컵경기장지점 MX관,20200623141135,영화관,0,서울특별시,마포구,성산동,515번지,"[월드컵쇼핑몰내, 1층]",메가박스중앙 주 상암월드컵경기장지점 MX관,메가박스중앙,"[주, , 상암월드컵경기장지점, MX관]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,영업중,0,서울특별시 성동구 성수동1가 656-335번지,메가박스중앙(주) 성수지점 더부티크 102호,20191213163233,영화관,20191106,서울특별시,성동구,성수동1가,656-335번지,[],메가박스중앙 주 성수지점 더부티크 102호,메가박스중앙,"[주, , 성수지점, 더부티크, 102호]"
130,영업중,0,서울특별시 성동구 성수동1가 656-335번지,메가박스중앙(주) 성수지점 MX관,20191213162857,영화관,20191106,서울특별시,성동구,성수동1가,656-335번지,[],메가박스중앙 주 성수지점 MX관,메가박스중앙,"[주, , 성수지점, MX관]"
131,영업중,0,서울특별시 성동구 성수동1가 656-335번지,메가박스중앙(주) 성수지점 2관,20191213162807,영화관,20191106,서울특별시,성동구,성수동1가,656-335번지,[],메가박스중앙 주 성수지점,메가박스중앙,"[주, , 성수지점]"
127,영업중,0,서울특별시 성동구 성수동1가 656-335번지,메가박스중앙(주) 성수지점 더부티크 101호,20191213163035,영화관,20191106,서울특별시,성동구,성수동1가,656-335번지,[],메가박스중앙 주 성수지점 더부티크 101호,메가박스중앙,"[주, , 성수지점, 더부티크, 101호]"
128,영업중,0,서울특별시 성동구 성수동1가 656-335번지,메가박스중앙(주) 성수지점 5관,20191213162959,영화관,20191106,서울특별시,성동구,성수동1가,656-335번지,[],메가박스중앙 주 성수지점,메가박스중앙,"[주, , 성수지점]"

In [42]:
# 주소 기준 같은 극장끼리 합치기
dup_data = data.drop_duplicates(['시', '구', '동', '번지', '극장', '상세영업상태명'], keep='first')
dup_data

,상세영업상태명,폐업일자,지번주소,사업장명,최종수정일자,공연장형태구분명,설립일자,시,구,동,번지,건물,new_사업장명,극장,관
654,폐업,20200916,서울특별시 중구 황학동 2545,롯데시네마 황학(제1관),20200917091427,영화관,0,서울특별시,중구,황학동,2545,[],롯데시네마 황학,롯데시네마,[황학]
327,영업중,0,서울특별시 마포구 동교동 159-8,CGV홍대 3관,20200827122024,영화관,0,서울특별시,마포구,동교동,159-8,[],CGV홍대,CGV홍대,[]
631,영업중,0,서울특별시 구로구 개봉동 339-9번지,샘물,20200820165701,영화관,0,서울특별시,구로구,개봉동,339-9번지,[],샘물,샘물,[]
619,영업중,0,서울특별시 마포구 성산동 515번지 월드컵쇼핑몰내 1층,메가박스중앙(주) 상암월드컵경기장지점 MX관,20200623141135,영화관,0,서울특별시,마포구,성산동,515번지,"[월드컵쇼핑몰내, 1층]",메가박스중앙 주 상암월드컵경기장지점 MX관,메가박스중앙,"[주, , 상암월드컵경기장지점, MX관]"
315,영업중,0,서울특별시 마포구 서교동 490 메세나폴리스 2층,롯데시네마 합정 제1관,20200805104901,영화관,0,서울특별시,마포구,서교동,490,"[메세나폴리스, 2층]",롯데시네마 합정,롯데시네마,[합정]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
527,영업중,0,서울특별시 강남구 삼성동 159번지 코엑스,코엑스지점 더 부티크 프라이빗,20191219144512,영화관,20180314,서울특별시,강남구,삼성동,159번지,"[코엑스, ]",코엑스지점 더 부티크 프라이빗,코엑스지점,"[더, 부티크, 프라이빗]"
372,영업중,0,서울특별시 강서구 등촌동 639-23번지 3~9층,CGV 등촌 4관,20191205111621,영화관,20190125,서울특별시,강서구,등촌동,639-23번지,"[3~9층, ]",CGV 등촌,CGV,[등촌]
208,영업중,0,서울특별시 성북구 동선동1가 1-2번지 유타,CGV 성신여대입구 2관,20190902114631,영화관,20190822,서울특별시,성북구,동선동1가,1-2번지,"[유타, ]",CGV 성신여대입구,CGV,[성신여대입구]
321,영업중,0,서울특별시 마포구 동교동 160-4번지 아일렉스,메가박스중앙(주) 홍대지점 2관,20191218104848,영화관,20190923,서울특별시,마포구,동교동,160-4번지,"[아일렉스, ]",메가박스중앙 주 홍대지점,메가박스중앙,"[주, , 홍대지점]"
129,영업중,0,서울특별시 성동구 성수동1가 656-335번지,메가박스중앙(주) 성수지점 4관,20191213162927,영화관,20191106,서울특별시,성동구,성수동1가,656-335번지,[],메가박스중앙 주 성수지점,메가박스중앙,"[주, , 성수지점]"

In [43]:
# 주소 기준 같은 주소끼리 합치기
dup_data2 = data.drop_duplicates(['시', '구', '동', '번지', '상세영업상태명'], keep='first')
dup_data2

,상세영업상태명,폐업일자,지번주소,사업장명,최종수정일자,공연장형태구분명,설립일자,시,구,동,번지,건물,new_사업장명,극장,관
654,폐업,20200916,서울특별시 중구 황학동 2545,롯데시네마 황학(제1관),20200917091427,영화관,0,서울특별시,중구,황학동,2545,[],롯데시네마 황학,롯데시네마,[황학]
327,영업중,0,서울특별시 마포구 동교동 159-8,CGV홍대 3관,20200827122024,영화관,0,서울특별시,마포구,동교동,159-8,[],CGV홍대,CGV홍대,[]
631,영업중,0,서울특별시 구로구 개봉동 339-9번지,샘물,20200820165701,영화관,0,서울특별시,구로구,개봉동,339-9번지,[],샘물,샘물,[]
619,영업중,0,서울특별시 마포구 성산동 515번지 월드컵쇼핑몰내 1층,메가박스중앙(주) 상암월드컵경기장지점 MX관,20200623141135,영화관,0,서울특별시,마포구,성산동,515번지,"[월드컵쇼핑몰내, 1층]",메가박스중앙 주 상암월드컵경기장지점 MX관,메가박스중앙,"[주, , 상암월드컵경기장지점, MX관]"
315,영업중,0,서울특별시 마포구 서교동 490 메세나폴리스 2층,롯데시네마 합정 제1관,20200805104901,영화관,0,서울특별시,마포구,서교동,490,"[메세나폴리스, 2층]",롯데시네마 합정,롯데시네마,[합정]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,영업중,0,서울특별시 중구 을지로6가 17-2번지 현대시티타워,CGV 동대문 제4관,20190424101812,영화관,20171219,서울특별시,중구,을지로6가,17-2번지,"[현대시티타워, ]",CGV 동대문,CGV,[동대문]
173,영업중,0,서울특별시 광진구 자양동 9-4번지 몰오브케이,CGV 건대입구 제2관,20190419105653,영화관,20180126,서울특별시,광진구,자양동,9-4번지,"[몰오브케이, ]",CGV 건대입구,CGV,[건대입구]
372,영업중,0,서울특별시 강서구 등촌동 639-23번지 3~9층,CGV 등촌 4관,20191205111621,영화관,20190125,서울특별시,강서구,등촌동,639-23번지,"[3~9층, ]",CGV 등촌,CGV,[등촌]
321,영업중,0,서울특별시 마포구 동교동 160-4번지 아일렉스,메가박스중앙(주) 홍대지점 2관,20191218104848,영화관,20190923,서울특별시,마포구,동교동,160-4번지,"[아일렉스, ]",메가박스중앙 주 홍대지점,메가박스중앙,"[주, , 홍대지점]"
129,영업중,0,서울특별시 성동구 성수동1가 656-335번지,메가박스중앙(주) 성수지점 4관,20191213162927,영화관,20191106,서울특별시,성동구,성수동1가,656-335번지,[],메가박스중앙 주 성수지점,메가박스중앙,"[주, , 성수지점]"

In [44]:
dup_data2.to_csv('data/영화관sub.csv', encoding='cp949', index=False)

### 6. 위경도 처리된 데이터 전처리
#### 1) 필요없는 컬럼 처리

In [51]:
geo_data = pd.read_csv('data/영화관(위경도).csv', encoding='cp949')
geo_data

,No,상세영업상태명,폐업일자,지번주소,사업장명,최종수정일자,공연장형태구분명,설립일자,시,구,동,번지,건물,new_사업장명,극장,관,경도,위도,상태
0,1,폐업,20200916,서울특별시 중구 황학동 2545,롯데시네마 황학(제1관),20200917091427,영화관,0,서울특별시,중구,황학동,2545,[],롯데시네마 황학,롯데시네마,[황학],127.021408,37.570969,정좌표
1,2,영업중,0,서울특별시 마포구 동교동 159-8,CGV홍대 3관,20200827122024,영화관,0,서울특별시,마포구,동교동,159-8,[],CGV홍대,CGV홍대,[],126.922732,37.556414,정좌표
2,3,영업중,0,서울특별시 구로구 개봉동 339-9번지,샘물,20200820165701,영화관,0,서울특별시,구로구,개봉동,339-9번지,[],샘물,샘물,[],126.852573,37.490112,정좌표
3,4,영업중,0,서울특별시 마포구 성산동 515번지 월드컵쇼핑몰내 1층,메가박스중앙(주) 상암월드컵경기장지점 MX관,20200623141135,영화관,0,서울특별시,마포구,성산동,515번지,"['월드컵쇼핑몰내', '1층']",메가박스중앙 주 상암월드컵경기장지점 MX관,메가박스중앙,"[주, , 상암월드컵경기장지점, MX관]",126.898385,37.569437,인근좌표
4,5,영업중,0,서울특별시 마포구 서교동 490 메세나폴리스 2층,롯데시네마 합정 제1관,20200805104901,영화관,0,서울특별시,마포구,서교동,490,"['메세나폴리스', '2층']",롯데시네마 합정,롯데시네마,[합정],126.913757,37.550924,정좌표
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,118,영업중,0,서울특별시 중구 을지로6가 17-2번지 현대시티타워,CGV 동대문 제4관,20190424101812,영화관,20171219,서울특별시,중구,을지로6가,17-2번지,"['현대시티타워', '']",CGV 동대문,CGV,[동대문],127.007707,37.568634,정좌표
118,119,영업중,0,서울특별시 광진구 자양동 9-4번지 몰오브케이,CGV 건대입구 제2관,20190419105653,영화관,20180126,서울특별시,광진구,자양동,9-4번지,"['몰오브케이', '']",CGV 건대입구,CGV,[건대입구],127.066910,37.539779,정좌표
119,120,영업중,0,서울특별시 강서구 등촌동 639-23번지 3~9층,CGV 등촌 4관,20191205111621,영화관,20190125,서울특별시,강서구,등촌동,639-23번지,"['3~9층', '']",CGV 등촌,CGV,[등촌],126.856021,37.557856,정좌표
120,121,영업중,0,서울특별시 마포구 동교동 160-4번지 아일렉스,메가박스중앙(주) 홍대지점 2관,20191218104848,영화관,20190923,서울특별시,마포구,동교동,160-4번지,"['아일렉스', '']",메가박스중앙 주 홍대지점,메가박스중앙,"[주, , 홍대지점]",126.922068,37.556056,정좌표
121,122,영업중,0,서울특별시 성동구 성수동1가 656-335번지,메가박스중앙(주) 성수지점 4관,20191213162927,영화관,20191106,서울특별시,성동구,성수동1가,656-335번지,[''],메가박스중앙 주 성수지점,메가박스중앙,"[주, , 성수지점]",127.044931,37.541861,정좌표

In [52]:
geo_data.drop(['No', '시', '구', '동', '번지', '극장', '관', '상태', '지번주소', 'new_사업장명', '건물', '최종수정일자'], axis=1, inplace=True)
geo_data

,상세영업상태명,폐업일자,사업장명,공연장형태구분명,설립일자,경도,위도
0,폐업,20200916,롯데시네마 황학(제1관),영화관,0,127.021408,37.570969
1,영업중,0,CGV홍대 3관,영화관,0,126.922732,37.556414
2,영업중,0,샘물,영화관,0,126.852573,37.490112
3,영업중,0,메가박스중앙(주) 상암월드컵경기장지점 MX관,영화관,0,126.898385,37.569437
4,영업중,0,롯데시네마 합정 제1관,영화관,0,126.913757,37.550924
...,...,...,...,...,...,...,...
117,영업중,0,CGV 동대문 제4관,영화관,20171219,127.007707,37.568634
118,영업중,0,CGV 건대입구 제2관,영화관,20180126,127.066910,37.539779
119,영업중,0,CGV 등촌 4관,영화관,20190125,126.856021,37.557856
120,영업중,0,메가박스중앙(주) 홍대지점 2관,영화관,20190923,126.922068,37.556056
121,영업중,0,메가박스중앙(주) 성수지점 4관,영화관,20191106,127.044931,37.541861

In [53]:
geo_data.to_csv('data/영화관(주소삭제).csv', encoding='cp949', index=False)

#### 2) 주소 새로 추가

In [54]:
ad_data = pd.read_csv('data/영화관(주소추가).csv', encoding='cp949')
ad_data

,No,상세영업상태명,폐업일자,사업장명,공연장형태구분명,설립일자,경도,위도,경도.1,지번주소,도로명주소
0,1,폐업,20200916,롯데시네마 황학(제1관),영화관,0,127.021408,37.570969,NaN,서울특별시 중구 황학동 2545,서울특별시 중구 청계천로 400
1,2,영업중,0,CGV홍대 3관,영화관,0,126.922732,37.556414,NaN,서울특별시 마포구 동교동 159-8,서울특별시 마포구 양화로 153
2,3,영업중,0,샘물,영화관,0,126.852573,37.490112,NaN,서울특별시 구로구 개봉동 339-9,서울특별시 구로구 개봉로15길 58-5
3,4,영업중,0,메가박스중앙(주) 상암월드컵경기장지점 MX관,영화관,0,126.898385,37.569437,NaN,서울특별시 마포구 성산동 515-1,서울특별시 마포구 월드컵로 240
4,5,영업중,0,롯데시네마 합정 제1관,영화관,0,126.913757,37.550924,NaN,서울특별시 마포구 서교동 490,서울특별시 마포구 양화로 45
...,...,...,...,...,...,...,...,...,...,...,...
117,118,영업중,0,CGV 동대문 제4관,영화관,20171219,127.007707,37.568634,NaN,서울특별시 중구 을지로6가 17-2,서울특별시 중구 을지로6가 장충단로13길 20
118,119,영업중,0,CGV 건대입구 제2관,영화관,20180126,127.066910,37.539779,NaN,서울특별시 광진구 자양동 9-4,서울특별시 광진구 아차산로30길 26
119,120,영업중,0,CGV 등촌 4관,영화관,20190125,126.856021,37.557856,NaN,서울특별시 강서구 등촌동 639-23,서울특별시 강서구 공항대로45길 63
120,121,영업중,0,메가박스중앙(주) 홍대지점 2관,영화관,20190923,126.922068,37.556056,NaN,서울특별시 마포구 동교동 160-4,서울특별시 마포구 양화로 147
121,122,영업중,0,메가박스중앙(주) 성수지점 4관,영화관,20191106,127.044931,37.541861,NaN,서울특별시 성동구 성수동1가 656-335,서울특별시 성동구 성수동1가 왕십리로 50

In [56]:
ad_data.drop(['No', '경도.1'], axis=1, inplace=True)
ad_data

,상세영업상태명,폐업일자,사업장명,공연장형태구분명,설립일자,경도,위도,지번주소,도로명주소
0,폐업,20200916,롯데시네마 황학(제1관),영화관,0,127.021408,37.570969,서울특별시 중구 황학동 2545,서울특별시 중구 청계천로 400
1,영업중,0,CGV홍대 3관,영화관,0,126.922732,37.556414,서울특별시 마포구 동교동 159-8,서울특별시 마포구 양화로 153
2,영업중,0,샘물,영화관,0,126.852573,37.490112,서울특별시 구로구 개봉동 339-9,서울특별시 구로구 개봉로15길 58-5
3,영업중,0,메가박스중앙(주) 상암월드컵경기장지점 MX관,영화관,0,126.898385,37.569437,서울특별시 마포구 성산동 515-1,서울특별시 마포구 월드컵로 240
4,영업중,0,롯데시네마 합정 제1관,영화관,0,126.913757,37.550924,서울특별시 마포구 서교동 490,서울특별시 마포구 양화로 45
...,...,...,...,...,...,...,...,...,...
117,영업중,0,CGV 동대문 제4관,영화관,20171219,127.007707,37.568634,서울특별시 중구 을지로6가 17-2,서울특별시 중구 을지로6가 장충단로13길 20
118,영업중,0,CGV 건대입구 제2관,영화관,20180126,127.066910,37.539779,서울특별시 광진구 자양동 9-4,서울특별시 광진구 아차산로30길 26
119,영업중,0,CGV 등촌 4관,영화관,20190125,126.856021,37.557856,서울특별시 강서구 등촌동 639-23,서울특별시 강서구 공항대로45길 63
120,영업중,0,메가박스중앙(주) 홍대지점 2관,영화관,20190923,126.922068,37.556056,서울특별시 마포구 동교동 160-4,서울특별시 마포구 양화로 147
121,영업중,0,메가박스중앙(주) 성수지점 4관,영화관,20191106,127.044931,37.541861,서울특별시 성동구 성수동1가 656-335,서울특별시 성동구 성수동1가 왕십리로 50

In [57]:
ad_data.to_csv('data/서울특별시 영화상영관 인허가 정보(NEW, cp949).csv', encoding='cp949', index=False)

### 7. 사업장명 처리된 데이터 전처리(2017~2019년, 2020년 데이터로 분리)
#### 1) 필요없는 컬럼 삭제

In [5]:
name_data = pd.read_csv('data/영화관/서울특별시 영화상영관 인허가 정보(사업장명, cp949).csv', encoding='cp949')
name_data

,상세영업상태명,폐업일자,사업장명,공연장형태구분명,설립일자,지번주소,도로명주소,경도,위도
0,폐업,20200916,롯데시네마 황학,영화관,0,서울특별시 중구 황학동 2545,서울특별시 중구 청계천로 400,127.021463,37.570809
1,영업중,0,CGV 홍대점,영화관,0,서울특별시 마포구 동교동 159-8,서울특별시 마포구 서교동 양화로 153,126.922632,37.556494
2,영업중,0,샘물,영화관,0,서울특별시 구로구 개봉동 339-9,서울특별시 구로구 개봉로15길 58-5,126.852595,37.490113
3,영업중,0,메가박스 상암월드컵경기장,영화관,0,서울특별시 마포구 성산동 515-1,서울특별시 마포구 월드컵로 240,126.899034,37.569943
4,영업중,0,롯데시네마 합정점,영화관,0,서울특별시 마포구 합정동 415-419,서울특별시 마포구 양화로 45,126.913678,37.550166
...,...,...,...,...,...,...,...,...,...
115,영업중,0,CGV 동대문,영화관,20171219,서울특별시 중구 을지로6가 17-2,서울특별시 중구 을지로6가 장충단로13길 20,127.007667,37.568736
116,영업중,0,CGV 건대입구,영화관,20180126,서울특별시 광진구 자양동 9-4,서울특별시 광진구 아차산로30길 26,127.066888,37.539761
117,영업중,0,CGV 등촌,영화관,20190125,서울특별시 강서구 등촌동 639-23,서울특별시 강서구 공항대로45길 63,126.856001,37.557869
118,영업중,0,메가박스 홍대,영화관,20190923,서울특별시 마포구 동교동 160-4,서울특별시 마포구 양화로 147,126.922053,37.556048
119,영업중,0,메가박스 성수,영화관,20191106,서울특별시 성동구 성수동1가 656-335,서울특별시 성동구 성수동1가 왕십리로 50,127.044911,37.541888

In [6]:
fin_data = name_data.drop_duplicates(['지번주소', '사업장명', '상세영업상태명'], keep='first').reset_index(drop=True)
fin_data

,상세영업상태명,폐업일자,사업장명,공연장형태구분명,설립일자,지번주소,도로명주소,경도,위도
0,폐업,20200916,롯데시네마 황학,영화관,0,서울특별시 중구 황학동 2545,서울특별시 중구 청계천로 400,127.021463,37.570809
1,영업중,0,CGV 홍대점,영화관,0,서울특별시 마포구 동교동 159-8,서울특별시 마포구 서교동 양화로 153,126.922632,37.556494
2,영업중,0,샘물,영화관,0,서울특별시 구로구 개봉동 339-9,서울특별시 구로구 개봉로15길 58-5,126.852595,37.490113
3,영업중,0,메가박스 상암월드컵경기장,영화관,0,서울특별시 마포구 성산동 515-1,서울특별시 마포구 월드컵로 240,126.899034,37.569943
4,영업중,0,롯데시네마 합정점,영화관,0,서울특별시 마포구 합정동 415-419,서울특별시 마포구 양화로 45,126.913678,37.550166
...,...,...,...,...,...,...,...,...,...
111,영업중,0,CGV 동대문,영화관,20171219,서울특별시 중구 을지로6가 17-2,서울특별시 중구 을지로6가 장충단로13길 20,127.007667,37.568736
112,영업중,0,CGV 건대입구,영화관,20180126,서울특별시 광진구 자양동 9-4,서울특별시 광진구 아차산로30길 26,127.066888,37.539761
113,영업중,0,CGV 등촌,영화관,20190125,서울특별시 강서구 등촌동 639-23,서울특별시 강서구 공항대로45길 63,126.856001,37.557869
114,영업중,0,메가박스 홍대,영화관,20190923,서울특별시 마포구 동교동 160-4,서울특별시 마포구 양화로 147,126.922053,37.556048
115,영업중,0,메가박스 성수,영화관,20191106,서울특별시 성동구 성수동1가 656-335,서울특별시 성동구 성수동1가 왕십리로 50,127.044911,37.541888

#### 2) 2017년 영업 여부 수정

In [9]:
df_2017 = fin_data[(fin_data['폐업일자']==0) | (fin_data['폐업일자']>20170101)]
df_2017 = df_2017[df_2017['설립일자']<20180101]
df_2017['년'] = 2017
df_2017

,상세영업상태명,폐업일자,사업장명,공연장형태구분명,설립일자,지번주소,도로명주소,경도,위도,년
0,폐업,20200916,롯데시네마 황학,영화관,0,서울특별시 중구 황학동 2545,서울특별시 중구 청계천로 400,127.021463,37.570809,2017
1,영업중,0,CGV 홍대점,영화관,0,서울특별시 마포구 동교동 159-8,서울특별시 마포구 서교동 양화로 153,126.922632,37.556494,2017
2,영업중,0,샘물,영화관,0,서울특별시 구로구 개봉동 339-9,서울특별시 구로구 개봉로15길 58-5,126.852595,37.490113,2017
3,영업중,0,메가박스 상암월드컵경기장,영화관,0,서울특별시 마포구 성산동 515-1,서울특별시 마포구 월드컵로 240,126.899034,37.569943,2017
4,영업중,0,롯데시네마 합정점,영화관,0,서울특별시 마포구 합정동 415-419,서울특별시 마포구 양화로 45,126.913678,37.550166,2017
...,...,...,...,...,...,...,...,...,...,...
107,영업중,0,롯데시네마 수유,영화관,20170424,서울특별시 강북구 번동 449-1,서울특별시 강북구 도봉로 308,127.023836,37.635665,2017
108,영업중,0,CGV 용산아이파크몰,영화관,20170714,서울특별시 용산구 한강로3가 40-961,서울특별시 용산구 한강로2가 청파로20길 43-8,126.965636,37.531653,2017
109,영업중,0,더숲 아트시네마,영화관,20170810,서울특별시 노원구 상계동 727-1,서울특별시 노원구 노해로 480,127.061435,37.654179,2017
110,영업중,0,메가박스 마곡,영화관,20170922,서울특별시 강서구 마곡동 797-1,서울특별시 강서구 공항대로 247,126.835240,37.559314,2017
111,영업중,0,CGV 동대문,영화관,20171219,서울특별시 중구 을지로6가 17-2,서울특별시 중구 을지로6가 장충단로13길 20,127.007667,37.568736,2017

In [10]:
open_df = df_2017[df_2017['폐업일자'] >= 20180101].reset_index(drop=True)
closed_df = df_2017[(df_2017['폐업일자'] == 0) |  (df_2017['폐업일자'] < 20180101)].reset_index(drop=True)
open_df

,상세영업상태명,폐업일자,사업장명,공연장형태구분명,설립일자,지번주소,도로명주소,경도,위도,년
0,폐업,20200916,롯데시네마 황학,영화관,0,서울특별시 중구 황학동 2545,서울특별시 중구 청계천로 400,127.021463,37.570809,2017
1,폐업,20180118,CGV 김포공항,영화관,20030122,서울특별시 강서구 방화동 886,서울특별시 강서구 개화동로 523,126.806147,37.565844,2017
2,폐업,20180716,메가박스 상암월드컵경기장,영화관,20030519,서울특별시 마포구 성산동 515,서울특별시 마포구 월드컵로 240,126.899034,37.569943,2017
3,폐업,20180824,서울애니시네마,영화관,20050823,서울특별시 중구 예장동 8-145,서울특별시 중구 소파로 126,126.987925,37.558397,2017
4,폐업,20190429,CGV 성신여대입구,영화관,20080911,서울특별시 성북구 동선동1가 1-2,서울특별시 성북구 동선동1가 동소문로 106,127.017088,37.592574,2017
5,폐업,20180705,KU시네마트랩,영화관,20120210,서울특별시 성북구 안암동5가 1-2,서울특별시 성북구 안암동5가 안암로 145,127.032685,37.587919,2017

In [11]:
open_df['폐업일자'] = 0
open_df['상세영업상태명'] = '영업중'
open_df

,상세영업상태명,폐업일자,사업장명,공연장형태구분명,설립일자,지번주소,도로명주소,경도,위도,년
0,영업중,0,롯데시네마 황학,영화관,0,서울특별시 중구 황학동 2545,서울특별시 중구 청계천로 400,127.021463,37.570809,2017
1,영업중,0,CGV 김포공항,영화관,20030122,서울특별시 강서구 방화동 886,서울특별시 강서구 개화동로 523,126.806147,37.565844,2017
2,영업중,0,메가박스 상암월드컵경기장,영화관,20030519,서울특별시 마포구 성산동 515,서울특별시 마포구 월드컵로 240,126.899034,37.569943,2017
3,영업중,0,서울애니시네마,영화관,20050823,서울특별시 중구 예장동 8-145,서울특별시 중구 소파로 126,126.987925,37.558397,2017
4,영업중,0,CGV 성신여대입구,영화관,20080911,서울특별시 성북구 동선동1가 1-2,서울특별시 성북구 동선동1가 동소문로 106,127.017088,37.592574,2017
5,영업중,0,KU시네마트랩,영화관,20120210,서울특별시 성북구 안암동5가 1-2,서울특별시 성북구 안암동5가 안암로 145,127.032685,37.587919,2017

In [12]:
fin_2017_df = pd.concat([open_df, closed_df], axis=0).reset_index(drop=True)
fin_2017_df.sort_values(by=['설립일자'], axis=0, inplace=True)
fin_2017_df

,상세영업상태명,폐업일자,사업장명,공연장형태구분명,설립일자,지번주소,도로명주소,경도,위도,년
0,영업중,0,롯데시네마 황학,영화관,0,서울특별시 중구 황학동 2545,서울특별시 중구 청계천로 400,127.021463,37.570809,2017
12,영업중,0,구로문화원,영화관,0,서울특별시 구로구 구로동 102,서울특별시 구로구 가마산로25길 21,126.889858,37.497201,2017
11,영업중,0,메가박스 코엑스,영화관,0,서울특별시 강남구 삼성동 159,서울특별시 강남구 봉은사로 524,127.057114,37.512944,2017
10,영업중,0,KT&G 상상마당 시네마,영화관,0,서울특별시 마포구 서교동 367-5,서울특별시 마포구 어울마당로 65,126.921063,37.550958,2017
8,영업중,0,메가박스 상암월드컵경기장,영화관,0,서울특별시 마포구 성산동 515-1,서울특별시 마포구 월드컵로 240,126.899034,37.569943,2017
...,...,...,...,...,...,...,...,...,...,...
107,영업중,0,롯데시네마 수유,영화관,20170424,서울특별시 강북구 번동 449-1,서울특별시 강북구 도봉로 308,127.023836,37.635665,2017
108,영업중,0,CGV 용산아이파크몰,영화관,20170714,서울특별시 용산구 한강로3가 40-961,서울특별시 용산구 한강로2가 청파로20길 43-8,126.965636,37.531653,2017
109,영업중,0,더숲 아트시네마,영화관,20170810,서울특별시 노원구 상계동 727-1,서울특별시 노원구 노해로 480,127.061435,37.654179,2017
110,영업중,0,메가박스 마곡,영화관,20170922,서울특별시 강서구 마곡동 797-1,서울특별시 강서구 공항대로 247,126.835240,37.559314,2017
111,영업중,0,CGV 동대문,영화관,20171219,서울특별시 중구 을지로6가 17-2,서울특별시 중구 을지로6가 장충단로13길 20,127.007667,37.568736,2017

#### 3) 2018년 영업 여부 수정

In [13]:
df_2018 = fin_data[(fin_data['폐업일자']==0) | (fin_data['폐업일자']>20180101)]
df_2018 = df_2018[df_2018['설립일자']<20190101]
df_2018['년'] = 2018
df_2018

,상세영업상태명,폐업일자,사업장명,공연장형태구분명,설립일자,지번주소,도로명주소,경도,위도,년
0,폐업,20200916,롯데시네마 황학,영화관,0,서울특별시 중구 황학동 2545,서울특별시 중구 청계천로 400,127.021463,37.570809,2018
1,영업중,0,CGV 홍대점,영화관,0,서울특별시 마포구 동교동 159-8,서울특별시 마포구 서교동 양화로 153,126.922632,37.556494,2018
2,영업중,0,샘물,영화관,0,서울특별시 구로구 개봉동 339-9,서울특별시 구로구 개봉로15길 58-5,126.852595,37.490113,2018
3,영업중,0,메가박스 상암월드컵경기장,영화관,0,서울특별시 마포구 성산동 515-1,서울특별시 마포구 월드컵로 240,126.899034,37.569943,2018
4,영업중,0,롯데시네마 합정점,영화관,0,서울특별시 마포구 합정동 415-419,서울특별시 마포구 양화로 45,126.913678,37.550166,2018
...,...,...,...,...,...,...,...,...,...,...
108,영업중,0,CGV 용산아이파크몰,영화관,20170714,서울특별시 용산구 한강로3가 40-961,서울특별시 용산구 한강로2가 청파로20길 43-8,126.965636,37.531653,2018
109,영업중,0,더숲 아트시네마,영화관,20170810,서울특별시 노원구 상계동 727-1,서울특별시 노원구 노해로 480,127.061435,37.654179,2018
110,영업중,0,메가박스 마곡,영화관,20170922,서울특별시 강서구 마곡동 797-1,서울특별시 강서구 공항대로 247,126.835240,37.559314,2018
111,영업중,0,CGV 동대문,영화관,20171219,서울특별시 중구 을지로6가 17-2,서울특별시 중구 을지로6가 장충단로13길 20,127.007667,37.568736,2018
112,영업중,0,CGV 건대입구,영화관,20180126,서울특별시 광진구 자양동 9-4,서울특별시 광진구 아차산로30길 26,127.066888,37.539761,2018

In [14]:
open_df = df_2018[df_2018['폐업일자'] >= 20190101].reset_index(drop=True)
closed_df = df_2018[(df_2018['폐업일자'] == 0) | (df_2018['폐업일자'] < 20190101)].reset_index(drop=True)
open_df

,상세영업상태명,폐업일자,사업장명,공연장형태구분명,설립일자,지번주소,도로명주소,경도,위도,년
0,폐업,20200916,롯데시네마 황학,영화관,0,서울특별시 중구 황학동 2545,서울특별시 중구 청계천로 400,127.021463,37.570809,2018
1,폐업,20190429,CGV 성신여대입구,영화관,20080911,서울특별시 성북구 동선동1가 1-2,서울특별시 성북구 동선동1가 동소문로 106,127.017088,37.592574,2018

In [15]:
open_df['폐업일자'] = 0
open_df['상세영업상태명'] = '영업중'
open_df

,상세영업상태명,폐업일자,사업장명,공연장형태구분명,설립일자,지번주소,도로명주소,경도,위도,년
0,영업중,0,롯데시네마 황학,영화관,0,서울특별시 중구 황학동 2545,서울특별시 중구 청계천로 400,127.021463,37.570809,2018
1,영업중,0,CGV 성신여대입구,영화관,20080911,서울특별시 성북구 동선동1가 1-2,서울특별시 성북구 동선동1가 동소문로 106,127.017088,37.592574,2018

In [17]:
fin_2018_df = pd.concat([open_df, closed_df], axis=0).reset_index(drop=True)
fin_2018_df.sort_values(by=['설립일자'], axis=0, inplace=True)

#### 3) 2019년 영업 여부 수정

In [18]:
df_2019 = fin_data[(fin_data['폐업일자']==0) | (fin_data['폐업일자']>20190101)]
df_2019 = df_2019[df_2019['설립일자']<20200101]
df_2019['년'] = 2019
df_2019

,상세영업상태명,폐업일자,사업장명,공연장형태구분명,설립일자,지번주소,도로명주소,경도,위도,년
0,폐업,20200916,롯데시네마 황학,영화관,0,서울특별시 중구 황학동 2545,서울특별시 중구 청계천로 400,127.021463,37.570809,2019
1,영업중,0,CGV 홍대점,영화관,0,서울특별시 마포구 동교동 159-8,서울특별시 마포구 서교동 양화로 153,126.922632,37.556494,2019
2,영업중,0,샘물,영화관,0,서울특별시 구로구 개봉동 339-9,서울특별시 구로구 개봉로15길 58-5,126.852595,37.490113,2019
3,영업중,0,메가박스 상암월드컵경기장,영화관,0,서울특별시 마포구 성산동 515-1,서울특별시 마포구 월드컵로 240,126.899034,37.569943,2019
4,영업중,0,롯데시네마 합정점,영화관,0,서울특별시 마포구 합정동 415-419,서울특별시 마포구 양화로 45,126.913678,37.550166,2019
...,...,...,...,...,...,...,...,...,...,...
111,영업중,0,CGV 동대문,영화관,20171219,서울특별시 중구 을지로6가 17-2,서울특별시 중구 을지로6가 장충단로13길 20,127.007667,37.568736,2019
112,영업중,0,CGV 건대입구,영화관,20180126,서울특별시 광진구 자양동 9-4,서울특별시 광진구 아차산로30길 26,127.066888,37.539761,2019
113,영업중,0,CGV 등촌,영화관,20190125,서울특별시 강서구 등촌동 639-23,서울특별시 강서구 공항대로45길 63,126.856001,37.557869,2019
114,영업중,0,메가박스 홍대,영화관,20190923,서울특별시 마포구 동교동 160-4,서울특별시 마포구 양화로 147,126.922053,37.556048,2019
115,영업중,0,메가박스 성수,영화관,20191106,서울특별시 성동구 성수동1가 656-335,서울특별시 성동구 성수동1가 왕십리로 50,127.044911,37.541888,2019

In [19]:
open_df = df_2019[df_2019['폐업일자'] >= 20200101].reset_index(drop=True)
closed_df = df_2019[(df_2019['폐업일자'] == 0) | (df_2019['폐업일자'] < 20200101)].reset_index(drop=True)
open_df

,상세영업상태명,폐업일자,사업장명,공연장형태구분명,설립일자,지번주소,도로명주소,경도,위도,년
0,폐업,20200916,롯데시네마 황학,영화관,0,서울특별시 중구 황학동 2545,서울특별시 중구 청계천로 400,127.021463,37.570809,2019

In [20]:
open_df['폐업일자'] = 0
open_df['상세영업상태명'] = '영업중'
open_df

,상세영업상태명,폐업일자,사업장명,공연장형태구분명,설립일자,지번주소,도로명주소,경도,위도,년
0,영업중,0,롯데시네마 황학,영화관,0,서울특별시 중구 황학동 2545,서울특별시 중구 청계천로 400,127.021463,37.570809,2019

In [22]:
fin_2019_df = pd.concat([open_df, closed_df], axis=0).reset_index(drop=True)
fin_2019_df.sort_values(by=['설립일자'], axis=0, inplace=True)

In [23]:
fin_df = pd.concat([fin_2017_df, fin_2018_df, fin_2019_df], axis=0).reset_index(drop=True)
fin_df = fin_df[['년', '상세영업상태명', '폐업일자', '사업장명', '공연장형태구분명', '설립일자', '지번주소', '도로명주소', '위도', '경도']]
fin_df

,년,상세영업상태명,폐업일자,사업장명,공연장형태구분명,설립일자,지번주소,도로명주소,위도,경도
0,2017,영업중,0,롯데시네마 황학,영화관,0,서울특별시 중구 황학동 2545,서울특별시 중구 청계천로 400,37.570809,127.021463
1,2017,영업중,0,구로문화원,영화관,0,서울특별시 구로구 구로동 102,서울특별시 구로구 가마산로25길 21,37.497201,126.889858
2,2017,영업중,0,메가박스 코엑스,영화관,0,서울특별시 강남구 삼성동 159,서울특별시 강남구 봉은사로 524,37.512944,127.057114
3,2017,영업중,0,KT&G 상상마당 시네마,영화관,0,서울특별시 마포구 서교동 367-5,서울특별시 마포구 어울마당로 65,37.550958,126.921063
4,2017,영업중,0,메가박스 상암월드컵경기장,영화관,0,서울특별시 마포구 성산동 515-1,서울특별시 마포구 월드컵로 240,37.569943,126.899034
...,...,...,...,...,...,...,...,...,...,...
322,2019,영업중,0,CGV 동대문,영화관,20171219,서울특별시 중구 을지로6가 17-2,서울특별시 중구 을지로6가 장충단로13길 20,37.568736,127.007667
323,2019,영업중,0,CGV 건대입구,영화관,20180126,서울특별시 광진구 자양동 9-4,서울특별시 광진구 아차산로30길 26,37.539761,127.066888
324,2019,영업중,0,CGV 등촌,영화관,20190125,서울특별시 강서구 등촌동 639-23,서울특별시 강서구 공항대로45길 63,37.557869,126.856001
325,2019,영업중,0,메가박스 홍대,영화관,20190923,서울특별시 마포구 동교동 160-4,서울특별시 마포구 양화로 147,37.556048,126.922053
326,2019,영업중,0,메가박스 성수,영화관,20191106,서울특별시 성동구 성수동1가 656-335,서울특별시 성동구 성수동1가 왕십리로 50,37.541888,127.044911

In [28]:
fin_df.to_csv('data/FIN/서울특별시 영화상영관 인허가 정보 2017-2019(전처리 완료, cp949).csv', encoding='cp949', index=False)

In [26]:
df_2020 = fin_data[(fin_data['폐업일자']==0) | (fin_data['폐업일자']>20200101)].reset_index(drop=True)
df_2020 = df_2020[df_2020['설립일자'] < 20210101]
df_2020['년'] = 2020
df_2020 = df_2020[['년', '상세영업상태명', '폐업일자', '사업장명', '공연장형태구분명', '설립일자', '지번주소', '도로명주소', '위도', '경도']]
df_2020

,년,상세영업상태명,폐업일자,사업장명,공연장형태구분명,설립일자,지번주소,도로명주소,위도,경도
0,2020,폐업,20200916,롯데시네마 황학,영화관,0,서울특별시 중구 황학동 2545,서울특별시 중구 청계천로 400,37.570809,127.021463
1,2020,영업중,0,CGV 홍대점,영화관,0,서울특별시 마포구 동교동 159-8,서울특별시 마포구 서교동 양화로 153,37.556494,126.922632
2,2020,영업중,0,샘물,영화관,0,서울특별시 구로구 개봉동 339-9,서울특별시 구로구 개봉로15길 58-5,37.490113,126.852595
3,2020,영업중,0,메가박스 상암월드컵경기장,영화관,0,서울특별시 마포구 성산동 515-1,서울특별시 마포구 월드컵로 240,37.569943,126.899034
4,2020,영업중,0,롯데시네마 합정점,영화관,0,서울특별시 마포구 합정동 415-419,서울특별시 마포구 양화로 45,37.550166,126.913678
...,...,...,...,...,...,...,...,...,...,...
101,2020,영업중,0,CGV 동대문,영화관,20171219,서울특별시 중구 을지로6가 17-2,서울특별시 중구 을지로6가 장충단로13길 20,37.568736,127.007667
102,2020,영업중,0,CGV 건대입구,영화관,20180126,서울특별시 광진구 자양동 9-4,서울특별시 광진구 아차산로30길 26,37.539761,127.066888
103,2020,영업중,0,CGV 등촌,영화관,20190125,서울특별시 강서구 등촌동 639-23,서울특별시 강서구 공항대로45길 63,37.557869,126.856001
104,2020,영업중,0,메가박스 홍대,영화관,20190923,서울특별시 마포구 동교동 160-4,서울특별시 마포구 양화로 147,37.556048,126.922053
105,2020,영업중,0,메가박스 성수,영화관,20191106,서울특별시 성동구 성수동1가 656-335,서울특별시 성동구 성수동1가 왕십리로 50,37.541888,127.044911

In [27]:
df_2020.to_csv('data/FIN/서울특별시 영화상영관 인허가 정보 2020(전처리 완료, cp949).csv', encoding='cp949', index=False)